import fs from "node:fs";
import path from "node:path";
import { ApprovalStore } from "./approval-store";
import { flattenToolSpecs, validateReleaseDataset } from "./dataset";
import { PublishedArtifactSchema, type PublishedArtifact } from "./published-artifact-schema";
import { sourceFingerprint } from "./orchestrator";
import { publicationText, validateForPublication } from "./validate";
import { LOCAL_ENGINES } from "../lib/studio/engines";

const ROOT = process.cwd();
const PUBLISHED_DIRECTORY = path.resolve(process.env.XFREE_PUBLISHED_DIR ?? path.join(ROOT, "content", "published"));
const DATASET_FILE = path.resolve(process.env.XFREE_DATASET_PATH ?? path.join(ROOT, "content", "dataset", "xfree-1500-v1.json"));
const APPROVAL_FILE = path.resolve(process.env.XFREE_APPROVAL_FILE ?? path.join(ROOT, "content-approvals.json"));
const REGISTRY_FILE = path.join(ROOT, "src", "data", "generatedPublishedContent.ts");

function writeRegistry(artifacts: readonly PublishedArtifact[]): void {
  const registry = Object.fromEntries(artifacts.map((artifact) => [artifact.slug, artifact]));
  const source = [
    "// AUTO-GENERATED BY src/content-pipeline/compile-published.ts. DO NOT EDIT.",
    'import type { PublishedArtifact } from "../content-pipeline/published-artifact-schema";',
    "",
    `export const GENERATED_PUBLISHED_CONTENT: Record<string, PublishedArtifact> = ${JSON.stringify(registry, null, 2)};`,
    "",
  ].join("\n");
  const temporary = `${REGISTRY_FILE}.tmp`;
  fs.writeFileSync(temporary, source, { encoding: "utf8", mode: 0o600 });
  fs.renameSync(temporary, REGISTRY_FILE);
}

export function compilePublishedArtifacts(): PublishedArtifact[] {
  if (!fs.existsSync(PUBLISHED_DIRECTORY)) {
    writeRegistry([]);
    return [];
  }
  const files = fs.readdirSync(PUBLISHED_DIRECTORY).filter((file) => file.endsWith(".json")).sort();
  if (files.length === 0) {
    writeRegistry([]);
    return [];
  }
  if (!fs.existsSync(DATASET_FILE)) throw new Error(`Published artifacts exist but the authoritative dataset is missing: ${DATASET_FILE}`);
  if (!fs.existsSync(APPROVAL_FILE)) throw new Error(`Published artifacts exist but the approval ledger is missing: ${APPROVAL_FILE}`);

  const datasetResult = validateReleaseDataset(JSON.parse(fs.readFileSync(DATASET_FILE, "utf8")));
  if (!datasetResult.valid || !datasetResult.dataset) throw new Error(`Release dataset failed validation: ${datasetResult.errors.join("; ")}`);
  const dataset = datasetResult.dataset;
  const specs = new Map(flattenToolSpecs(dataset).map((spec) => [spec.slug, spec]));
  const approvals = new ApprovalStore(APPROVAL_FILE);
  const engineIds = new Set(LOCAL_ENGINES.map((engine) => engine.id));
  const corpus: Array<{ slug: string; text: string }> = [];
  const compiled: PublishedArtifact[] = [];

  for (const file of files) {
    const artifact = PublishedArtifactSchema.parse(JSON.parse(fs.readFileSync(path.join(PUBLISHED_DIRECTORY, file), "utf8")));
    const spec = specs.get(artifact.slug);
    if (!spec || spec.pillarSlug !== artifact.pillarSlug) throw new Error(`Artifact ${artifact.slug} is absent from its declared dataset pillar`);
    if (sourceFingerprint(spec) !== artifact.sourceFingerprint) throw new Error(`Source fingerprint mismatch for ${artifact.slug}`);
    const approval = approvals.get(artifact.slug);
    if (!approval || approval.contentFingerprint !== artifact.contentFingerprint) throw new Error(`Approval mismatch for ${artifact.slug}`);

    const result = validateForPublication(
      { ...spec, content: artifact.content, metadata: { h1: artifact.metadata.h1, title: artifact.metadata.title, description: artifact.metadata.description } },
      { availableStudioEngineIds: engineIds, similarityCorpus: corpus, approval },
    );
    if (result.status !== "published" || result.contentFingerprint !== artifact.contentFingerprint) {
      throw new Error(`Publication gates no longer pass for ${artifact.slug}: ${result.errors.join("; ")}`);
    }
    if (result.studioDeepLink !== artifact.studioDeepLink) throw new Error(`Studio deep-link mismatch for ${artifact.slug}`);
    compiled.push(artifact);
    corpus.push({ slug: artifact.slug, text: publicationText(result.candidate!) });
  }

  writeRegistry(compiled);
  return compiled;
}

const compiled = compilePublishedArtifacts();
console.log(`Compiled ${compiled.length} approved generated tool page(s).`);
