import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const seoTools = [
  // URL Manipulation (1-15)
  ["bulk-url-extractor", "bulk url extractor", "Bulk URL Extractor", "Extract all URLs and links from webpage source HTML or raw text into clean lists.", ["extract urls from webpage", "url extractor online", "link scraper"], "BulkUrlExtractor"],
  ["url-encoder-decoder", "url encoder decoder", "URL Encoder/Decoder", "Encode or decode special characters in URLs according to RFC 3986 specs.", ["url encode online", "url decode online", "percent encoding tool"], "UrlSlugUtmBuilder"],
  ["url-shortener-free", "url shortener free", "Free URL Shortener", "Shorten long web links into concise, shareable URLs.", ["shorten link free", "custom url shortener", "link shortener"], "UrlSlugUtmBuilder"],
  ["url-expander-online", "url expander online", "URL Expander", "Reveal the true destination of shortened or redirected URLs safely.", ["unshorten url", "check redirect destination", "url expander"], "UrlSlugUtmBuilder"],
  ["url-parser-online", "url parser online", "URL Parser", "Parse and inspect protocol, hostname, port, path, and query parameters of any URL.", ["url breakdown tool", "parse url parameters", "url structure analyzer"], "UrlSlugUtmBuilder"],
  ["url-slug-generator", "url slug generator", "URL Slug Generator", "Convert page titles and phrases into clean, SEO-friendly URL slugs.", ["slugify title", "seo slug creator", "clean url builder"], "UrlSlugUtmBuilder"],
  ["utm-builder", "utm builder", "UTM Campaign Builder", "Build tracked Google Analytics campaign URLs with source, medium, campaign, and term tags.", ["google utm builder", "tracking link creator", "utm parameter generator"], "UrlSlugUtmBuilder"],
  ["utm-analyzer", "utm analyzer", "UTM Analyzer & Debugger", "Parse, analyze, and validate UTM tracking parameters from marketing campaign links.", ["parse utm parameters", "decode utm link", "utm validator"], "UrlSlugUtmBuilder"],
  ["canonical-url-checker", "canonical url checker", "Canonical URL Checker", "Inspect canonical tags on target URLs to verify self-referencing and consolidation.", ["check canonical tag", "canonical tag tester", "rel canonical checker"], "MetaOpenGraphGenerator"],
  ["redirect-chain-checker", "redirect chain checker", "Redirect Chain Checker", "Trace 301 and 302 HTTP redirect chains and identify redirect loops.", ["trace redirect path", "301 redirect checker", "redirect loop detector"], "BulkUrlExtractor"],
  ["broken-link-checker-free", "broken link checker free", "Broken Link Checker", "Identify broken links, 404 errors, and dead URLs across webpages.", ["404 link checker", "dead link finder", "check website links"], "BulkUrlExtractor"],
  ["http-status-checker", "http status checker", "HTTP Status Code Checker", "Test HTTP response status codes (200, 301, 302, 404, 500) for target web links.", ["check http status", "header response checker", "url status test"], "BulkUrlExtractor"],
  ["url-to-ip", "url to ip", "URL to IP Converter", "Resolve domain names and web URLs to server IP addresses instantly.", ["domain to ip lookup", "website ip resolver", "dns ip check"], "UrlSlugUtmBuilder"],
  ["ip-to-url", "ip to url", "IP to Hostname Converter", "Perform reverse DNS lookup to find domain names associated with IP addresses.", ["reverse dns lookup", "ip to domain", "ip host finder"], "UrlSlugUtmBuilder"],
  ["url-parameter-builder", "url parameter builder", "URL Parameter Builder", "Easily append, modify, and format query parameters on target web URLs.", ["build query string", "append url parameters", "query string builder"], "UrlSlugUtmBuilder"],

  // Sitemap & Robots (16-28)
  ["xml-sitemap-generator", "xml sitemap generator", "XML Sitemap Generator", "Generate Google-compliant XML sitemaps automatically from link lists or crawl text.", ["free sitemap creator", "sitemap index builder", "xml sitemap tool"], "BulkUrlExtractor"],
  ["sitemap-validator", "sitemap validator", "Sitemap Validator", "Validate XML sitemap syntax, check tag structure, and detect broken URLs.", ["check xml sitemap", "sitemap error checker", "validate sitemap xml"], "BulkUrlExtractor"],
  ["sitemap-index-generator", "sitemap index generator", "Sitemap Index Generator", "Combine multiple XML sitemap files into a master Google sitemap index.", ["sitemap index builder", "merge sitemaps", "master sitemap creator"], "BulkUrlExtractor"],
  ["html-sitemap-generator", "html sitemap generator", "HTML Sitemap Generator", "Convert URL collections into structured HTML sitemap pages for site navigation.", ["visual sitemap creator", "html link directory", "user sitemap maker"], "BulkUrlExtractor"],
  ["video-sitemap-generator", "video sitemap generator", "Video Sitemap Generator", "Generate specialized XML video sitemaps with thumbnail, title, and duration metadata.", ["video sitemap builder", "google video sitemap", "video seo schema"], "BulkUrlExtractor"],
  ["image-sitemap-generator", "image sitemap generator", "Image Sitemap Generator", "Build image XML sitemaps to enhance Google Image Search indexing.", ["image sitemap builder", "google image sitemap", "photo sitemap tool"], "BulkUrlExtractor"],
  ["news-sitemap-generator", "news sitemap generator", "Google News Sitemap Generator", "Create Google News compliant XML sitemaps with publication name and date fields.", ["google news sitemap", "news article sitemap", "publisher sitemap"], "BulkUrlExtractor"],
  ["robots-txt-generator", "robots.txt generator", "Robots.txt Generator", "Generate customized robots.txt files with crawl-delay and user-agent disallow rules.", ["create robots.txt", "robots txt builder", "googlebot disallow creator"], "RobotsTxtGenerator"],
  ["robots-txt-tester", "robots.txt tester", "Robots.txt Tester", "Test user-agent access rules against robots.txt directives to check crawlability.", ["test robots.txt rules", "robots txt validator", "check googlebot access"], "RobotsTxtGenerator"],
  ["sitemap-splitter", "sitemap splitter", "Sitemap Splitter", "Split massive XML sitemaps containing over 50,000 URLs into smaller chunks.", ["split large sitemap", "chunk xml sitemap", "sitemap file divider"], "BulkUrlExtractor"],
  ["sitemap-url-extractor", "sitemap url extractor", "Sitemap URL Extractor", "Parse and extract all individual URL locations from XML sitemap files.", ["extract urls from sitemap", "parse sitemap xml", "sitemap link scraper"], "BulkUrlExtractor"],
  ["sitemap-to-csv", "sitemap to csv", "Sitemap to CSV Converter", "Convert XML sitemap links, lastmod dates, and priorities into CSV spreadsheets.", ["sitemap csv exporter", "export sitemap to excel", "xml sitemap to table"], "BulkUrlExtractor"],
  ["csv-to-sitemap", "csv to sitemap", "CSV to Sitemap Converter", "Convert CSV URL lists into valid XML sitemaps ready for Search Console submission.", ["csv to xml sitemap", "build sitemap from csv", "excel to sitemap"], "BulkUrlExtractor"],

  // Meta Tags & Schema (29-45)
  ["meta-tag-generator", "meta tag generator", "Meta Tag Generator", "Create optimized HTML title tags, meta descriptions, and viewport configurations.", ["seo meta tag builder", "create meta tags", "html meta tag tool"], "MetaOpenGraphGenerator"],
  ["open-graph-generator", "open graph generator", "Open Graph Meta Generator", "Generate og:title, og:image, and og:description tags for Facebook and LinkedIn.", ["og tag generator", "facebook meta tags", "social preview builder"], "MetaOpenGraphGenerator"],
  ["twitter-card-generator", "twitter card generator", "Twitter Card Generator", "Create summary and large image Twitter Card meta tags for X/Twitter sharing.", ["x card generator", "twitter meta tags", "twitter preview tool"], "MetaOpenGraphGenerator"],
  ["serp-preview-tool", "serp preview tool", "SERP Snippet Preview", "Preview how your title, meta description, and URL will appear in Google Search results.", ["google search preview", "serp snippet simulator", "title description preview"], "MetaOpenGraphGenerator"],
  ["title-tag-generator", "title tag generator", "Title Tag Generator", "Generate catchy, keyword-rich SEO title tags within character and pixel limits.", ["seo title maker", "click-worthy title creator", "headline tag builder"], "MetaOpenGraphGenerator"],
  ["meta-description-generator", "meta description generator", "Meta Description Generator", "Draft high-converting meta descriptions optimized for 155-character limits.", ["seo description builder", "meta snippet writer", "search description maker"], "MetaOpenGraphGenerator"],
  ["schema-markup-generator", "schema markup generator", "Schema Markup Generator", "Build JSON-LD structured data markup for Google Rich Results.", ["schema org builder", "json-ld markup creator", "rich snippet generator"], "SchemaGenerator"],
  ["json-ld-generator", "json-ld generator", "JSON-LD Generator", "Create clean JSON-LD scripts for structured data search engine optimization.", ["json ld builder", "structured data generator", "google json-ld maker"], "SchemaGenerator"],
  ["faq-schema-generator", "faq schema generator", "FAQ Schema Generator", "Generate FAQPage JSON-LD schema to secure FAQ rich snippets in Google SERPs.", ["faq page schema", "faq rich snippet creator", "json-ld faq builder"], "SchemaGenerator"],
  ["howto-schema-generator", "howto schema generator", "HowTo Schema Generator", "Create HowTo structured data markup with step-by-step instructions and images.", ["how to schema builder", "how-to rich snippet", "json ld howto maker"], "SchemaGenerator"],
  ["product-schema-generator", "product schema generator", "Product Schema Generator", "Build Product JSON-LD schema with price, rating, availability, and review fields.", ["ecommerce schema creator", "product rich snippet", "json ld product tool"], "SchemaGenerator"],
  ["article-schema-generator", "article schema generator", "Article Schema Generator", "Generate NewsArticle and BlogPosting JSON-LD schema markup for blog posts.", ["blog schema generator", "news article schema", "article rich snippet"], "SchemaGenerator"],
  ["recipe-schema-generator", "recipe schema generator", "Recipe Schema Generator", "Create Recipe schema markup with cooking time, ingredients, and nutrition info.", ["recipe rich snippet", "food blog schema maker", "cooking schema generator"], "SchemaGenerator"],
  ["video-schema-generator", "video schema generator", "Video Schema Generator", "Build VideoObject JSON-LD markup with embed URLs, thumbnails, and upload dates.", ["video object schema", "video rich snippet creator", "youtube video schema"], "SchemaGenerator"],
  ["local-business-schema", "local business schema", "Local Business Schema Generator", "Create LocalBusiness structured data with NAP info, geo coordinates, and hours.", ["local seo schema builder", "gmb schema creator", "json ld local business"], "SchemaGenerator"],
  ["breadcrumb-schema", "breadcrumb schema", "Breadcrumb Schema Generator", "Generate BreadcrumbList JSON-LD schema to show clean breadcrumbs in Google SERPs.", ["breadcrumb list schema", "json-ld breadcrumb maker", "serp breadcrumbs"], "SchemaGenerator"],
  ["organization-schema", "organization schema", "Organization Schema Generator", "Build Organization JSON-LD markup with company logo, social profiles, and contact.", ["company schema builder", "organization rich snippet", "json ld organization"], "SchemaGenerator"],

  // Keyword & Content Analysis (46-62)
  ["keyword-density-checker", "keyword density checker", "Keyword Density Checker", "Analyze word frequency, 1-3 word phrase density, and keyword stuffing risk.", ["check keyword density", "word frequency analyzer", "seo content density"], "WordCounter"],
  ["keyword-grouping-tool", "keyword grouping tool", "Keyword Grouping Tool", "Group list of keywords into tight semantic clusters for content strategy.", ["keyword clustering tool", "group search terms", "keyword categorization"], "WordCounter"],
  ["long-tail-keyword-generator", "long tail keyword generator", "Long Tail Keyword Generator", "Discover high-intent long-tail keyword variations for low-competition ranking.", ["find long tail keywords", "niche keyword finder", "search query generator"], "WordCounter"],
  ["keyword-cluster-tool", "keyword cluster tool", "Keyword Cluster Tool", "Group keywords into topical clusters based on search intent and semantic overlaps.", ["topical authority builder", "keyword matrix generator", "semantic cluster maker"], "WordCounter"],
  ["search-intent-classifier", "search intent classifier", "Search Intent Classifier", "Classify keywords into Informational, Navigational, Commercial, or Transactional intent.", ["intent analysis tool", "determine search intent", "keyword intent checker"], "WordCounter"],
  ["lsi-keyword-generator", "lsi keyword generator", "LSI Keyword Generator", "Find Latent Semantic Indexing (LSI) terms to enrich blog content context.", ["semantic keywords finder", "lsi terms creator", "related term generator"], "WordCounter"],
  ["keyword-difficulty-checker", "keyword difficulty checker", "Keyword Difficulty Checker", "Evaluate organic search competition and keyword ranking difficulty estimates.", ["check keyword difficulty", "seo difficulty score", "keyword competition tool"], "WordCounter"],
  ["serp-keyword-extractor", "serp keyword extractor", "SERP Keyword Extractor", "Extract top keywords, headings, and terms from search engine result snippets.", ["serp term scraper", "search result keyword finder", "serp content analyzer"], "WordCounter"],
  ["people-also-ask-extractor", "people also ask extractor", "People Also Ask Extractor", "Scrape and extract questions from Google's People Also Ask (PAA) boxes.", ["extract google paa", "find search questions", "paa scraper tool"], "WordCounter"],
  ["related-keywords-finder", "related keywords finder", "Related Keywords Finder", "Discover related search queries and search suggestions for core seed keywords.", ["google search suggestions", "find related queries", "keyword ideas maker"], "WordCounter"],
  ["hashtag-generator", "hashtag generator", "Hashtag Generator", "Generate trending hashtags for Instagram, TikTok, LinkedIn, and X/Twitter.", ["social hashtag creator", "viral hashtag finder", "instagram tag builder"], "WordCounter"],
  ["youtube-tag-extractor", "youtube tag extractor", "YouTube Tag Extractor", "Extract video tags and keywords from any YouTube video URL.", ["scrape youtube tags", "youtube keyword finder", "video tag scraper"], "WordCounter"],
  ["amazon-keyword-tool", "amazon keyword tool", "Amazon Keyword Tool", "Generate Amazon auto-suggest search terms for e-commerce product SEO.", ["amazon seo keywords", "product search tags", "amazon listing keywords"], "WordCounter"],
  ["etsy-tag-generator", "etsy tag generator", "Etsy Tag Generator", "Find high-converting tags and search keywords for Etsy shop product listings.", ["etsy listing tags", "handmade product keywords", "etsy seo generator"], "WordCounter"],
  ["pinterest-keyword-tool", "pinterest keyword tool", "Pinterest Keyword Tool", "Discover high-volume Pinterest search terms for pin descriptions and boards.", ["pinterest search tags", "pin keyword generator", "pinterest seo tool"], "WordCounter"],
  ["tiktok-hashtag-generator", "tiktok hashtag generator", "TikTok Hashtag Generator", "Find viral TikTok hashtags and sound trends to maximize video reach.", ["tiktok video tags", "trending tiktok hashtags", "tiktok seo tool"], "WordCounter"],
  ["meta-keywords-generator", "meta keywords generator", "Meta Keywords Generator", "Extract core tags and generate meta keywords lists for document categorization.", ["create meta keywords", "extract document tags", "page keyword tagger"], "WordCounter"],

  // Technical SEO & Audits (63-80)
  ["seo-analyzer-free", "seo analyzer free", "Website SEO Analyzer", "Perform on-page SEO audits, inspect tags, image alt text, and heading structure.", ["free seo audit tool", "website health check", "on page seo checker"], "BulkUrlExtractor"],
  ["page-speed-analyzer", "page speed analyzer", "Page Speed Analyzer", "Analyze webpage performance metrics and identify speed bottlenecks.", ["test load speed", "website speed checker", "performance auditor"], "BulkUrlExtractor"],
  ["core-web-vitals-test", "core web vitals test", "Core Web Vitals Tester", "Measure LCP, FID/INP, and CLS scores for desktop and mobile page user experience.", ["check core web vitals", "lcp cls analyzer", "google web vitals test"], "BulkUrlExtractor"],
  ["mobile-friendly-test", "mobile friendly test", "Mobile Friendly Test", "Inspect viewport tags, text readability, and touch targets for mobile usability.", ["check mobile responsiveness", "responsive design test", "mobile usability audit"], "BulkUrlExtractor"],
  ["ssl-checker-online", "ssl checker online", "SSL Certificate Checker", "Check SSL/TLS certificate validity, expiration date, issuer, and cipher suite.", ["test ssl certificate", "https validity check", "ssl expiry inspector"], "BulkUrlExtractor"],
  ["dns-propagation-checker", "dns propagation checker", "DNS Propagation Checker", "Verify global DNS record propagation across multiple DNS servers worldwide.", ["global dns check", "dns propagation test", "check domain propagation"], "BulkUrlExtractor"],
  ["dns-lookup-tool", "dns lookup tool", "DNS Record Lookup", "Query A, AAAA, MX, CNAME, TXT, and NS records for any domain name.", ["lookup dns records", "query mx records", "domain dns query"], "BulkUrlExtractor"],
  ["whois-lookup-free", "whois lookup free", "WHOIS Lookup Tool", "Inspect domain registration details, registrar, creation date, and expiration.", ["domain whois lookup", "check domain owner", "domain age lookup"], "BulkUrlExtractor"],
  ["domain-age-checker", "domain age checker", "Domain Age Checker", "Calculate exact age, registration date, and domain domain authority history.", ["check age of domain", "domain history lookup", "domain creation date"], "BulkUrlExtractor"],
  ["backlink-checker-free", "backlink checker free", "Backlink Checker", "Analyze incoming referring domains and backlink profiles for web domains.", ["check domain backlinks", "referring sites finder", "inbound link checker"], "BulkUrlExtractor"],
  ["domain-authority-checker", "domain authority checker", "Domain Authority Checker", "Estimate domain authority, trust score, and domain ranking potential.", ["check da score", "domain rating checker", "website trust score"], "BulkUrlExtractor"],
  ["page-authority-checker", "page authority checker", "Page Authority Checker", "Analyze individual page authority scores and ranking strength.", ["check pa score", "page rating inspector", "url authority score"], "BulkUrlExtractor"],
  ["spam-score-checker", "spam score checker", "Spam Score Checker", "Evaluate domain link spam flags and potential toxic backlink penalties.", ["check website spam score", "link toxicity checker", "seo penalty check"], "BulkUrlExtractor"],
  ["hreflang-generator", "hreflang generator", "Hreflang Tag Generator", "Generate hreflang link tags for multi-language and multi-regional websites.", ["multi language seo tag", "hreflang builder", "language alternate tags"], "MetaOpenGraphGenerator"],
  ["hreflang-validator", "hreflang validator", "Hreflang Validator", "Validate hreflang implementation, return tags, and ISO language/region codes.", ["check hreflang syntax", "hreflang auditor", "test language tags"], "MetaOpenGraphGenerator"],
  ["internal-link-analyzer", "internal link analyzer", "Internal Link Analyzer", "Audit internal link counts, anchor text diversity, and link architecture.", ["check internal links", "link depth analyzer", "internal page rank"], "BulkUrlExtractor"],
  ["orphan-page-finder", "orphan page finder", "Orphan Page Finder", "Identify unlinked orphan pages that lack internal inbound links.", ["find orphan pages", "unlinked page detector", "crawl audit tool"], "BulkUrlExtractor"],
  ["duplicate-content-checker", "duplicate content checker", "Duplicate Content Checker", "Compare webpage text to identify internal or external content duplication.", ["check copied content", "plagiarism seo tool", "content similarity check"], "TextDiffChecker"],

  // International & Local SEO (81-92)
  ["local-seo-checker", "local seo checker", "Local SEO Checker", "Audit local citations, NAP consistency, and local map pack rank signals.", ["local search audit", "nap consistency check", "local pack analyzer"], "SchemaGenerator"],
  ["gmb-optimizer", "gmb optimizer", "Google My Business Optimizer", "Optimize GMB listing profile info, categories, and business description tags.", ["gmb audit tool", "google business profile optimizer", "local listing tool"], "SchemaGenerator"],
  ["nap-consistency-checker", "nap consistency checker", "NAP Consistency Checker", "Verify Name, Address, and Phone accuracy across top local business directories.", ["check nap consistency", "local citation audit", "directory nap check"], "SchemaGenerator"],
  ["citation-finder", "citation finder", "Citation Finder", "Discover local citation opportunities and niche directory submission sites.", ["find local citations", "business directory finder", "local backlink finder"], "SchemaGenerator"],
  ["multilingual-seo-tool", "multilingual seo tool", "Multi-language SEO Tool", "Optimize international content alternate tags, canonicals, and language targets.", ["international seo tool", "multilingual tag generator", "global seo optimizer"], "MetaOpenGraphGenerator"],
  ["country-code-extractor", "country code extractor", "Country Code Extractor", "Extract ISO 2-letter and 3-letter country codes from URLs, TLDs, or address lists.", ["iso country code finder", "tld country extractor", "country code lookup"], "CaseConverter"],
  ["currency-locale-detector", "currency locale detector", "Currency Locale Detector", "Detect currency codes, symbols, and formatting rules based on country locale.", ["currency formatting tool", "locale detector", "currency code lookup"], "CaseConverter"],
  ["timezone-seo-tool", "timezone seo tool", "Timezone SEO Tool", "Calculate optimal publish times and schedule posts across global timezones.", ["global publish scheduler", "timezone posting tool", "seo time converter"], "CronExpressionGenerator"],
  ["geo-targeting-tester", "geo targeting tester", "Geo Targeting Tester", "Test search result rendering across different geographic IP locations.", ["test geo search results", "location based search", "ip search tester"], "BulkUrlExtractor"],
  ["ip-geolocation", "ip geolocation", "IP Geolocation Tool", "Lookup geographic location, country, city, and ISP information for any IP address.", ["ip location finder", "check ip country", "geolocation lookup"], "UrlSlugUtmBuilder"],
  ["cdn-tester", "cdn tester", "CDN Tester", "Test Content Delivery Network response headers, edge caching, and TTFB latency.", ["check cdn caching", "edge latency test", "cdn header inspector"], "BulkUrlExtractor"],
  ["tld-analyzer", "tld analyzer", "TLD Analyzer", "Analyze top-level domain extensions (.com, .io, .ai) for search engine trust.", ["tld trust score", "domain extension analyzer", "check tld authority"], "UrlSlugUtmBuilder"],

  // Reporting & Analytics (93-100)
  ["seo-report-generator", "seo report generator", "SEO Report Generator", "Generate comprehensive PDF and CSV audit reports for clients and stakeholders.", ["client seo report", "audit report maker", "export seo audit"], "BulkUrlExtractor"],
  ["competitor-analysis-tool", "competitor analysis tool", "Competitor Analysis Tool", "Compare keyword overlap, content length, and meta tags against organic competitors.", ["seo competitor comparison", "domain gap analysis", "competitor keyword check"], "WordCounter"],
  ["serp-tracker-free", "serp tracker free", "SERP Tracker", "Track target keyword positions in Google Search results over time.", ["rank tracking tool", "check serp position", "organic rank tracker"], "WordCounter"],
  ["rank-checker-free", "rank checker free", "Rank Checker", "Check live search engine rankings for target domain keywords.", ["check google ranking", "keyword rank lookup", "live serp rank"], "WordCounter"],
  ["keyword-position-tracker", "keyword position tracker", "Keyword Position Tracker", "Monitor fluctuations in organic search result rankings.", ["position fluctuation checker", "rank tracker free", "serp monitor"], "WordCounter"],
  ["traffic-estimator", "traffic estimator", "Traffic Estimator", "Estimate organic search traffic potential based on monthly search volumes.", ["calculate organic traffic", "traffic volume calculator", "search volume estimator"], "WordCounter"],
  ["seo-roi-calculator", "seo roi calculator", "SEO ROI Calculator", "Calculate projected return on investment for organic search SEO campaigns.", ["calculate seo roi", "seo revenue estimator", "organic search roi"], "WordCounter"],
  ["seo-audit-checklist", "seo audit checklist", "SEO Audit Checklist", "Interactive 50-point technical, content, and link SEO audit checklist.", ["technical audit checklist", "on page seo checklist", "website audit guide"], "BulkUrlExtractor"]
];

const developerTools = [
  // Formatters (1-15)
  ["json-formatter", "json formatter", "JSON Formatter", "Format, beautify, validate, and minify JSON payloads with syntax highlighting.", ["json validator", "json minifier", "json beautifier"], "JsonFormatterValidator"],
  ["json-validator", "json validator", "JSON Validator", "Validate JSON syntax, highlight errors, and fix structural malformations.", ["json error checker", "validate json online", "json parser test"], "JsonFormatterValidator"],
  ["json-minifier", "json minifier", "JSON Minifier", "Compress and minify JSON files by removing whitespace and line breaks.", ["compress json", "json size reducer", "minify json online"], "JsonFormatterValidator"],
  ["xml-formatter", "xml formatter", "XML Formatter", "Format, beautify, and indent XML documents with custom spacing options.", ["xml beautifier", "format xml online", "xml auto indent"], "JsonFormatterValidator"],
  ["xml-validator", "xml validator", "XML Validator", "Validate XML document syntax and verify closing tag compliance.", ["xml error checker", "check xml syntax", "xml parser validator"], "JsonFormatterValidator"],
  ["xml-minifier", "xml minifier", "XML Minifier", "Minify XML payloads to reduce network transfer payload sizes.", ["compress xml", "xml minifier online", "strip xml whitespace"], "JsonFormatterValidator"],
  ["yaml-formatter", "yaml formatter", "YAML Formatter", "Format, lint, and indent YAML configuration files for Kubernetes and Docker.", ["yaml lint", "format yaml online", "yaml beautifier"], "JsonFormatterValidator"],
  ["yaml-validator", "yaml validator", "YAML Validator", "Validate YAML file syntax and indentation error detection.", ["yaml error checker", "check yaml syntax", "validate yaml online"], "JsonFormatterValidator"],
  ["sql-formatter", "sql formatter", "SQL Formatter", "Format, beautify, and standardize SQL queries for MySQL, Postgres, and Oracle.", ["sql beautifier", "format sql online", "sql query indent"], "SqlFormatterValidator"],
  ["sql-beautifier", "sql beautifier", "SQL Beautifier", "Transform messy SQL code into clean, readable formatted query blocks.", ["beautify sql queries", "clean sql code", "pretty print sql"], "SqlFormatterValidator"],
  ["html-formatter", "html formatter", "HTML Formatter", "Format and auto-indent raw HTML source code with clean nesting.", ["html beautifier", "format html code", "html indent tool"], "MarkdownEditorPreview"],
  ["html-minifier", "html minifier", "HTML Minifier", "Minify HTML documents by stripping comments, spaces, and line breaks.", ["compress html", "html code minifier", "reduce html size"], "MarkdownEditorPreview"],
  ["css-formatter", "css formatter", "CSS Formatter", "Format and expand compressed CSS stylesheets into structured rules.", ["css beautifier", "format css stylesheet", "pretty print css"], "TextDiffChecker"],
  ["css-minifier", "css minifier", "CSS Minifier", "Compress CSS files to optimize page load speeds and bandwidth usage.", ["minify css code", "compress stylesheet", "css size optimizer"], "TextDiffChecker"],
  ["javascript-formatter", "javascript formatter", "JavaScript Formatter", "Format, beautify, and un-minify obfuscated JavaScript code.", ["js beautifier", "format javascript code", "js auto indent"], "TextDiffChecker"],

  // Converters (16-30)
  ["json-to-csv", "json to csv", "JSON to CSV Converter", "Convert JSON arrays and nested API responses into structured CSV spreadsheets.", ["export json to excel", "json to table", "convert json csv"], "JsonFormatterValidator"],
  ["csv-to-json", "csv to json", "CSV to JSON Converter", "Convert CSV spreadsheet files and tables into clean JSON object arrays.", ["excel to json", "csv array to json", "table to json converter"], "JsonFormatterValidator"],
  ["json-to-xml", "json to xml", "JSON to XML Converter", "Transform JSON data payloads into well-formed XML documents.", ["convert json to xml", "json xml converter", "json tree to xml"], "JsonFormatterValidator"],
  ["xml-to-json", "xml to json", "XML to JSON Converter", "Convert XML documents and RSS feeds into JSON object format.", ["convert xml to json", "xml parser to json", "rss to json"], "JsonFormatterValidator"],
  ["json-to-yaml", "json to yaml", "JSON to YAML Converter", "Convert JSON data into clean YAML config format for Docker and CI/CD.", ["json to yaml online", "convert json yaml", "json to yml"], "JsonFormatterValidator"],
  ["yaml-to-json", "yaml to json", "YAML to JSON Converter", "Convert YAML config files into structured JSON payloads.", ["yaml to json converter", "convert yml to json", "parse yaml json"], "JsonFormatterValidator"],
  ["json-to-toml", "json to toml", "JSON to TOML Converter", "Convert JSON documents into TOML configuration format.", ["json to toml online", "convert json toml", "toml builder"], "JsonFormatterValidator"],
  ["csv-to-sql", "csv to sql", "CSV to SQL Converter", "Generate SQL INSERT INTO statements from CSV spreadsheet rows.", ["csv to insert sql", "convert excel to sql", "csv to database"], "SqlFormatterValidator"],
  ["sql-to-csv", "sql to csv", "SQL to CSV Converter", "Convert SQL query results and dump files into downloadable CSV tables.", ["export sql to excel", "sql dump to csv", "convert query csv"], "SqlFormatterValidator"],
  ["markdown-to-html", "markdown to html", "Markdown to HTML Converter", "Convert GFM Markdown text into formatted HTML markup.", ["md to html converter", "render markdown html", "markdown compiler"], "MarkdownEditorPreview"],
  ["html-to-markdown", "html to markdown", "HTML to Markdown Converter", "Convert HTML pages and web snippets into clean Markdown code.", ["html to md", "web page to markdown", "convert html md"], "MarkdownEditorPreview"],
  ["markdown-to-pdf", "markdown to pdf", "Markdown to PDF Converter", "Convert Markdown documentation files into styled PDF documents.", ["md to pdf exporter", "export markdown pdf", "markdown document print"], "MarkdownEditorPreview"],
  ["html-to-pdf", "html to pdf", "HTML to PDF Converter", "Render raw HTML and CSS stylesheets into downloadable PDF pages.", ["html web to pdf", "save html as pdf", "convert web page pdf"], "MarkdownEditorPreview"],
  ["ini-to-json", "ini to json", "INI to JSON Converter", "Convert INI configuration files into structured JSON objects.", ["ini file to json", "parse ini to json", "convert ini config"], "JsonFormatterValidator"],
  ["properties-to-json", "properties to json", "Properties to JSON Converter", "Convert Java .properties config files into nested JSON objects.", ["java properties to json", "convert properties file", "parse properties json"], "JsonFormatterValidator"],

  // Encoding & Hashing (31-48)
  ["base64-encoder", "base64 encoder", "Base64 Encoder", "Encode text, binary strings, or images into Base64 format.", ["encode base64 online", "text to base64", "base64 converter"], "Base64JwtDecoder"],
  ["base64-decoder", "base64 decoder", "Base64 Decoder", "Decode Base64 encoded strings back into plain text or data files.", ["decode base64 online", "base64 to text", "base64 string decoder"], "Base64JwtDecoder"],
  ["url-encoder", "url encoder", "URL Encoder", "Percent-encode special characters in query string parameter values.", ["percent encoder", "url string encode", "encode uri component"], "UrlSlugUtmBuilder"],
  ["url-decoder", "url decoder", "URL Decoder", "Decode percent-encoded URL query string parameters back to plain text.", ["percent decoder", "url string decode", "decode uri component"], "UrlSlugUtmBuilder"],
  ["html-entity-encoder", "html entity encoder", "HTML Entity Encoder", "Convert HTML characters like <, >, and & into safety encoded entities.", ["encode html entities", "escape html characters", "html entity maker"], "TextDiffChecker"],
  ["html-entity-decoder", "html entity decoder", "HTML Entity Decoder", "Decode HTML entities like &lt; and &amp; back into readable characters.", ["decode html entities", "unescape html code", "html entity parser"], "TextDiffChecker"],
  ["md5-generator", "md5 generator", "MD5 Hash Generator", "Generate 128-bit MD5 checksum hashes for text or input verification.", ["md5 checksum generator", "text to md5", "calculate md5 hash"], "HashGenerator"],
  ["sha1-generator", "sha1 generator", "SHA-1 Hash Generator", "Calculate SHA-1 cryptographic hashes for text payloads.", ["sha1 checksum maker", "generate sha1 hash", "sha1 string encoder"], "HashGenerator"],
  ["sha256-generator", "sha256 generator", "SHA-256 Hash Generator", "Generate secure SHA-256 hashes for data integrity verification.", ["sha256 hash maker", "text to sha256", "calculate sha256"], "HashGenerator"],
  ["sha512-generator", "sha512 generator", "SHA-512 Hash Generator", "Generate high-security SHA-512 cryptographic hash digest strings.", ["sha512 checksum maker", "calculate sha512", "sha512 hash generator"], "HashGenerator"],
  ["bcrypt-generator", "bcrypt generator", "Bcrypt Hash Generator", "Generate secure salted Bcrypt password hashes with custom work factors.", ["bcrypt hash maker", "password bcrypt generator", "bcrypt salt tool"], "HashGenerator"],
  ["argon2-generator", "argon2 generator", "Argon2 Hash Generator", "Generate Argon2id secure password hashes for web auth systems.", ["argon2 password hash", "argon2id generator", "argon2 checksum"], "HashGenerator"],
  ["hmac-generator", "hmac generator", "HMAC Generator", "Calculate Hash-based Message Authentication Codes with secret keys.", ["hmac sha256 generator", "calculate hmac code", "hmac signature maker"], "HashGenerator"],
  ["uuid-generator", "uuid generator", "UUID v4 Generator", "Generate bulk cryptographically secure v4 UUID unique identifiers.", ["guid generator online", "create random uuid", "uuid v4 builder"], "PasswordGenerator"],
  ["ulid-generator", "ulid generator", "ULID Generator", "Generate Universally Unique Lexicographically Sortable Identifiers.", ["ulid generator online", "sortable unique id", "ulid creator"], "PasswordGenerator"],
  ["nanoid-generator", "nanoid generator", "NanoID Generator", "Generate tiny, secure, URL-friendly unique string IDs.", ["nanoid builder", "small unique id generator", "nanoid maker"], "PasswordGenerator"],
  ["cuid-generator", "cuid generator", "CUID Generator", "Generate collision-resistant IDs optimized for horizontal scaling.", ["cuid generator online", "cuid2 maker", "database id generator"], "PasswordGenerator"],
  ["snowflake-id-generator", "snowflake id generator", "Snowflake ID Generator", "Generate 64-bit Twitter Snowflake time-sortable integer IDs.", ["twitter snowflake generator", "64 bit integer id", "snowflake id maker"], "PasswordGenerator"],

  // Testing & Debugging (49-62)
  ["regex-tester", "regex tester", "Regex Tester", "Test regular expressions with real-time match group highlighting.", ["regex pattern tester", "regex validator", "test regular expression"], "RegexTesterExplainer"],
  ["regex-generator-ai", "regex generator", "AI Regex Generator", "Generate regular expression patterns from natural language prompts.", ["ai regex maker", "plain text to regex", "regex prompt builder"], "AiRegexGenerator"],
  ["regex-explainer", "regex explainer", "Regex Explainer", "Deconstruct complex regular expressions into human readable explanations.", ["explain regex pattern", "regex syntax guide", "breakdown regex"], "RegexTesterExplainer"],
  ["xpath-tester", "xpath tester", "XPath Tester", "Test XPath query expressions against XML and HTML document trees.", ["test xpath query", "xml xpath evaluator", "xpath expression test"], "JsonFormatterValidator"],
  ["jsonpath-tester", "jsonpath tester", "JSONPath Tester", "Evaluate JSONPath query expressions against JSON objects.", ["test jsonpath query", "jsonpath evaluator", "query json payload"], "JsonFormatterValidator"],
  ["jwt-decoder", "jwt decoder", "JWT Decoder", "Decode JSON Web Tokens and inspect header and payload claims.", ["decode jwt online", "jwt payload inspector", "parse json web token"], "Base64JwtDecoder"],
  ["jwt-debugger", "jwt debugger", "JWT Debugger", "Debug and verify JWT signatures with secret keys or RSA public keys.", ["verify jwt signature", "debug jwt token", "jwt security inspector"], "Base64JwtDecoder"],
  ["curl-converter", "curl converter", "cURL Converter", "Convert cURL commands into JavaScript fetch, Python requests, or Go code.", ["curl to fetch", "curl to python requests", "convert curl command"], "TextDiffChecker"],
  ["postman-to-code", "postman to code", "Postman Collection Converter", "Convert Postman JSON collections into executable API client code.", ["postman to javascript", "convert postman collection", "postman client generator"], "JsonFormatterValidator"],
  ["har-analyzer", "har analyzer", "HAR File Analyzer", "Parse HTTP Archive (HAR) files to audit network request timings.", ["parse har file", "har network log viewer", "analyze har performance"], "JsonFormatterValidator"],
  ["webhook-tester", "webhook tester", "Webhook Tester", "Inspect incoming HTTP POST requests, headers, and webhook payloads.", ["test incoming webhook", "webhook payload debugger", "http request log"], "JsonFormatterValidator"],
  ["cors-tester", "cors tester", "CORS Tester", "Test Cross-Origin Resource Sharing headers for target API endpoints.", ["check cors headers", "cors error debugger", "test access control allow origin"], "UrlSlugUtmBuilder"],
  ["http-request-builder", "http request builder", "HTTP Request Builder", "Build, test, and send custom HTTP REST requests from your browser.", ["rest api tester", "send http request online", "browser api client"], "JsonFormatterValidator"],
  ["graphql-query-builder", "graphql query builder", "GraphQL Query Builder", "Compose, test, and format GraphQL queries and variables.", ["graphql query tester", "build graphql query", "format graphql"], "JsonFormatterValidator"],

  // Time & Scheduling (63-72)
  ["cron-generator", "cron generator", "Cron Expression Generator", "Build 5-part crontab schedules with human readable schedule descriptions.", ["crontab builder", "create cron schedule", "cron expression maker"], "CronExpressionGenerator"],
  ["cron-explainer", "cron explainer", "Cron Expression Explainer", "Convert crontab schedule expressions into plain English schedules.", ["explain cron schedule", "cron to human readable", "parse cron expression"], "CronExpressionGenerator"],
  ["timestamp-converter", "timestamp converter", "Unix Timestamp Converter", "Convert Unix epoch timestamps to UTC and local human-readable datetime.", ["epoch to date", "date to epoch", "timestamp to readable date"], "UnixTimestampConverter"],
  ["epoch-to-date", "epoch to date", "Epoch to Date Converter", "Convert numeric epoch seconds or milliseconds to standard datetime strings.", ["convert epoch seconds", "unix epoch to utc", "epoch time calculator"], "UnixTimestampConverter"],
  ["date-to-epoch", "date to epoch", "Date to Epoch Converter", "Convert human-readable calendar dates and times into Unix epoch timestamps.", ["convert date to timestamp", "date to epoch seconds", "calendar to epoch"], "UnixTimestampConverter"],
  ["timezone-converter", "timezone converter", "Timezone Converter", "Convert meeting times and dates between global world timezones.", ["convert timezones", "world time converter", "pst to est converter"], "UnixTimestampConverter"],
  ["date-difference-calculator", "date difference calculator", "Date Difference Calculator", "Calculate exact days, hours, and minutes between two dates.", ["days between dates", "calculate date difference", "time duration between dates"], "UnixTimestampConverter"],
  ["business-days-calculator", "business days calculator", "Business Days Calculator", "Calculate work days and exclude weekends and holidays between dates.", ["calculate working days", "business days count", "exclude weekends calculator"], "UnixTimestampConverter"],
  ["iso-8601-converter", "iso 8601 converter", "ISO 8601 Date Converter", "Format and parse standard ISO 8601 timestamp strings.", ["format iso 8601", "iso date parser", "utc iso timestamp"], "UnixTimestampConverter"],
  ["rfc-3339-converter", "rfc 3339 converter", "RFC 3339 Converter", "Convert and validate RFC 3339 formatted Internet timestamps.", ["format rfc 3339", "rfc date parser", "internet timestamp tool"], "UnixTimestampConverter"],

  // Generators & Utilities (73-88)
  ["password-generator", "password generator", "Password Generator", "Generate cryptographically secure random passwords with customizable parameters.", ["secure password maker", "random password generator", "strong password builder"], "PasswordGenerator"],
  ["password-strength-checker", "password strength checker", "Password Strength Checker", "Evaluate password entropy bits and estimate brute-force cracking times.", ["check password entropy", "test password security", "password vulnerability tool"], "PasswordGenerator"],
  ["random-number-generator", "random number generator", "Random Number Generator", "Generate single or bulk random numbers within a min/max range.", ["rng tool", "random integer picker", "generate numbers"], "PasswordGenerator"],
  ["random-string-generator", "random string generator", "Random String Generator", "Generate random alphanumeric strings for API keys and secrets.", ["random string maker", "generate secret token", "random alphanumeric string"], "PasswordGenerator"],
  ["random-word-generator", "random word generator", "Random Word Generator", "Generate lists of random English words for brainstorming and testing.", ["random word picker", "generate words", "brainstorming word list"], "WordCounter"],
  ["lorem-ipsum-generator", "lorem ipsum generator", "Lorem Ipsum Generator", "Generate placeholder dummy text paragraphs, sentences, or words.", ["dummy text generator", "lorem ipsum text maker", "placeholder text"], "WordCounter"],
  ["fake-data-generator", "fake data generator", "Fake Data Generator", "Generate mock names, emails, addresses, and phone numbers for test databases.", ["mock database data", "synthetic user data", "generate test data"], "JsonFormatterValidator"],
  ["qr-code-generator", "qr code generator", "QR Code Generator", "Generate high-resolution vector QR codes for URLs, WiFi, and vCards.", ["create qr code", "custom qr code maker", "vector qr code"], "QrCodeGenerator"],
  ["barcode-generator", "barcode generator", "Barcode Generator", "Generate CODE128, EAN-13, and UPC barcodes for product packaging.", ["create barcode online", "code128 generator", "ean barcode builder"], "QrCodeGenerator"],
  ["favicon-generator", "favicon generator", "Favicon Generator", "Convert logos into ICO and PNG favicon bundles for web browsers.", ["convert image to favicon", "create ico favicon", "web icon generator"], "QrCodeGenerator"],
  ["chmod-calculator", "chmod calculator", "Chmod Calculator", "Calculate Linux file permissions in octal (755, 644) and symbolic notation.", ["linux chmod calculator", "file permissions converter", "octal chmod tool"], "Base64JwtDecoder"],
  ["mime-type-lookup", "mime type lookup", "MIME Type Lookup", "Find Content-Type MIME headers for file extensions.", ["mime type database", "file extension content type", "check mime header"], "Base64JwtDecoder"],
  ["http-status-codes", "http status codes", "HTTP Status Reference", "Interactive quick reference for all 1xx, 2xx, 3xx, 4xx, and 5xx HTTP codes.", ["http status code list", "rest api error codes", "http response guide"], "UrlSlugUtmBuilder"],
  ["user-agent-parser", "user-agent parser", "User Agent Parser", "Parse User-Agent strings to extract browser version, OS, and device type.", ["decode user agent", "browser detection tool", "parse user agent string"], "Base64JwtDecoder"],
  ["git-command-generator", "git command generator", "Git Command Generator", "Generate Git commands for branch merging, rebase, cherry-pick, and stash.", ["git helper tool", "create git commands", "git syntax generator"], "TextDiffChecker"],
  ["commit-message-generator", "commit message generator", "Git Commit Message Generator", "Format conventional commit messages (feat, fix, docs, chore).", ["conventional commits maker", "format git commit", "commit message helper"], "TextDiffChecker"],

  // CSS & Design Dev Tools (89-100)
  ["css-gradient-generator", "css gradient generator", "CSS Gradient Generator", "Create linear, radial, and conic CSS gradients with instant CSS code export.", ["css gradient background", "linear gradient maker", "css color gradient"], "ColorPaletteContrastChecker"],
  ["box-shadow-generator", "box shadow generator", "CSS Box Shadow Generator", "Design smooth CSS box-shadow effects with horizontal, vertical, blur, and spread controls.", ["css shadow generator", "custom box shadow maker", "drop shadow generator"], "ColorPaletteContrastChecker"],
  ["text-shadow-generator", "text shadow generator", "CSS Text Shadow Generator", "Create subtle text depth and glow effects with custom CSS text-shadow rules.", ["css text shadow maker", "text shadow generator", "css font glow"], "ColorPaletteContrastChecker"],
  ["border-radius-generator", "border radius generator", "CSS Border Radius Generator", "Build rounded corners and custom organic shape CSS border-radius curves.", ["css rounded corners", "fancy border radius", "border radius preview"], "ColorPaletteContrastChecker"],
  ["css-filter-generator", "css filter generator", "CSS Filter Generator", "Apply blur, brightness, contrast, grayscale, and hue-rotate filters visually.", ["css image filters", "css filter generator", "visual filter builder"], "ColorPaletteContrastChecker"],
  ["flexbox-playground", "flexbox playground", "CSS Flexbox Playground", "Interactive flex container playground to test flex-direction, justify-content, and align-items.", ["css flexbox visualizer", "flexbox alignment test", "learn flexbox css"], "ColorPaletteContrastChecker"],
  ["css-grid-playground", "css grid playground", "CSS Grid Playground", "Visual grid generator to design responsive template columns, rows, and gap layouts.", ["css grid layout builder", "visual css grid maker", "grid template columns"], "ColorPaletteContrastChecker"],
  ["css-animation-generator", "css animation generator", "CSS Keyframe Animation Generator", "Design CSS keyframe animations with easing curves and keyframe steps.", ["css keyframes generator", "animate css builder", "css transition maker"], "ColorPaletteContrastChecker"],
  ["css-button-generator", "css button generator", "CSS Button Generator", "Design call-to-action buttons with hover states, gradients, and borders.", ["css cta button maker", "custom button generator", "design css button"], "ColorPaletteContrastChecker"],
  ["color-converter", "color converter", "Color Converter (HEX/RGB/HSL)", "Convert color codes between HEX, RGB, HSL, HSV, and CMYK color spaces.", ["hex to rgb converter", "rgb to hsl converter", "color code converter"], "ColorPaletteContrastChecker"],
  ["color-contrast-checker", "color contrast checker", "Color Contrast Checker", "Verify WCAG 2.1 AA/AAA text color contrast ratios against background fills.", ["wcag contrast checker", "color accessibility test", "text contrast ratio"], "ColorPaletteContrastChecker"],
  ["css-unit-converter", "css unit converter", "CSS Unit Converter (PX/REM/EM)", "Convert layout values between PX, REM, EM, VW, VH, and percentage units.", ["px to rem converter", "rem to px calculator", "css font size converter"], "ColorPaletteContrastChecker"]
];

const aiTools = [
  // AI Code Tools (1-18)
  ["ai-regex-generator", "ai regex generator", "AI Regex Generator", "Generate regular expressions from plain language prompts using Gemini AI.", ["ai regex builder", "regex prompt to pattern", "generate regex ai"], "AiMicroTool"],
  ["ai-regex-explainer", "ai regex explainer", "AI Regex Explainer", "Explain complex regular expressions line-by-line using AI.", ["explain regex ai", "regex breakdown ai", "deconstruct regex pattern"], "AiMicroTool"],
  ["ai-sql-generator", "ai sql generator", "AI SQL Generator", "Convert plain English requests into optimized SQL database queries.", ["text to sql query ai", "ai sql builder", "generate database query"], "AiMicroTool"],
  ["ai-sql-error-explainer", "ai sql error explainer", "AI SQL Error Explainer", "Debug database error logs and fix SQL syntax errors automatically.", ["fix sql error ai", "debug database query", "sql error assistant"], "AiMicroTool"],
  ["ai-code-generator", "ai code generator", "AI Code Generator", "Generate TypeScript, Python, or Go code snippets from natural text specifications.", ["generate code ai", "text to code converter", "ai coding assistant"], "AiMicroTool"],
  ["ai-code-explainer", "ai code explainer", "AI Code Explainer", "Explain complex functions and legacy codebases in plain English.", ["explain code ai", "understand code snippet", "ai code tutor"], "AiMicroTool"],
  ["ai-code-converter", "ai code converter", "AI Code Converter", "Translate code between programming languages (e.g. Python to TypeScript).", ["convert code language", "translate code ai", "python to js converter"], "AiMicroTool"],
  ["ai-code-reviewer", "ai code reviewer", "AI Code Reviewer", "Review code snippets for security bugs, performance bottlenecks, and best practices.", ["ai pull request review", "code quality audit", "ai code inspector"], "AiMicroTool"],
  ["ai-code-optimizer", "ai code optimizer", "AI Code Optimizer", "Refactor code to improve execution speed, memory efficiency, and readability.", ["optimize code speed", "refactor code ai", "clean code optimizer"], "AiMicroTool"],
  ["ai-bug-detector", "ai bug detector", "AI Bug Detector", "Detect runtime exceptions, logic errors, and memory leaks in source code.", ["find code bugs ai", "debug runtime error", "code vulnerability scan"], "AiMicroTool"],
  ["ai-test-case-generator", "ai test case generator", "AI Test Case Generator", "Generate unit test cases and mock assertions for Jest, PyTest, or JUnit.", ["generate unit tests", "jest test case builder", "ai test generator"], "AiMicroTool"],
  ["ai-documentation-generator", "ai documentation generator", "AI Documentation Generator", "Generate comprehensive JSDoc, Docstrings, and Markdown docs from source code.", ["create code docs", "jsdoc generator ai", "auto documentation maker"], "AiMicroTool"],
  ["ai-api-doc-generator", "ai api doc generator", "AI API Doc Generator", "Generate OpenAPI / Swagger documentation from raw REST JSON payloads.", ["openapi generator ai", "swagger doc creator", "api reference maker"], "AiMicroTool"],
  ["ai-readme-generator", "ai readme generator", "AI README Generator", "Create professional GitHub README.md files with installation steps and badges.", ["github readme builder", "markdown readme generator", "create repo readme"], "AiMicroTool"],
  ["ai-commit-message", "ai commit message", "AI Commit Message Generator", "Draft Conventional Commit messages from raw git diff outputs.", ["generate commit message", "git diff to commit", "conventional commit ai"], "AiMicroTool"],
  ["ai-pr-description", "ai pr description", "AI PR Description Generator", "Generate Pull Request summary descriptions from commit histories.", ["github pr generator", "pull request summary", "draft pr description"], "AiMicroTool"],
  ["ai-code-refactoring", "ai code refactoring", "AI Code Refactorer", "Refactor monolithic functions into clean, modular TypeScript patterns.", ["refactor code ai", "modular code builder", "clean architecture refactor"], "AiMicroTool"],
  ["ai-function-name-generator", "ai function name generator", "AI Function Name Generator", "Suggest clean, descriptive variable and function names based on code logic.", ["variable name generator", "clean code naming", "function naming helper"], "AiMicroTool"],

  // AI Data & JSON Tools (19-30)
  ["ai-json-repair", "ai json repair", "AI JSON Repair Tool", "Repair truncated or malformed JSON payloads and trailing commas.", ["fix broken json ai", "repair json syntax", "json sanitizer ai"], "AiMicroTool"],
  ["ai-xml-repair", "ai xml repair", "AI XML Repair Tool", "Fix unclosed tags and invalid entity references in XML documents.", ["fix broken xml ai", "repair xml syntax", "xml sanitizer ai"], "AiMicroTool"],
  ["ai-csv-cleaner", "ai csv cleaner", "AI CSV Cleaner", "Deduplicate, normalize, and fix malformed rows in CSV data spreadsheets.", ["clean csv data ai", "csv row sanitizer", "fix csv formatting"], "AiMicroTool"],
  ["ai-data-normalizer", "ai data normalizer", "AI Data Normalizer", "Standardize date formats, phone numbers, and addresses across datasets.", ["normalize dataset ai", "format data fields", "data cleaning tool"], "AiMicroTool"],
  ["ai-schema-generator", "ai schema generator", "AI Schema Generator", "Generate TypeScript interfaces, Zod schemas, or JSON Schema from data.", ["generate typescript interface", "zod schema builder", "json schema creator"], "AiMicroTool"],
  ["ai-mock-data-generator", "ai mock data generator", "AI Mock Data Generator", "Generate realistic synthetic datasets for testing and database seeding.", ["generate mock data", "fake dataset builder", "synthetic data creator"], "AiMicroTool"],
  ["ai-api-response-generator", "ai api response generator", "AI API Response Generator", "Generate realistic REST and GraphQL API mock responses.", ["mock api response", "fake REST json", "api endpoint mock"], "AiMicroTool"],
  ["ai-log-analyzer", "ai log analyzer", "AI Log Analyzer", "Analyze server error logs and stack traces to highlight root cause issues.", ["parse error logs ai", "stack trace analyzer", "server log debugger"], "AiMicroTool"],
  ["ai-error-message-generator", "ai error message generator", "AI Error Message Generator", "Draft user-friendly error messages and troubleshooting hints for software apps.", ["user friendly error text", "ui error message maker", "error hint generator"], "AiMicroTool"],
  ["ai-exception-handler", "ai exception handler", "AI Exception Handler", "Generate robust try/catch exception handling code for async workflows.", ["try catch builder", "async error handling", "exception safety code"], "AiMicroTool"],
  ["ai-data-anonymizer", "ai data anonymizer", "AI Data Anonymizer", "Mask and redact Personally Identifiable Information (PII) from logs and data.", ["pii redactor ai", "anonymize text data", "mask sensitive info"], "AiMicroTool"],
  ["ai-table-extractor", "ai table extractor", "AI Table Extractor", "Extract tabular data from raw text or markdown into structured JSON/CSV.", ["extract text to table", "convert text to csv ai", "table parser ai"], "AiMicroTool"],

  // AI Content & SEO Tools (31-50)
  ["ai-meta-optimizer", "ai meta optimizer", "AI Meta Description Optimizer", "Optimize meta descriptions for target primary keywords and CTR.", ["optimize meta tags ai", "seo meta writer", "click-worthy description"], "AiMicroTool"],
  ["ai-title-optimizer", "ai title optimizer", "AI Title Tag Optimizer", "Generate high-CTR, keyword-dense page titles optimized for search engines.", ["optimize title tags", "seo title writer", "headline optimizer ai"], "AiMicroTool"],
  ["ai-slug-generator", "ai slug generator", "AI Slug Generator", "Create short, keyword-rich URL slugs for new blog posts and landing pages.", ["seo url slug maker", "generate blog slug", "clean URL creator"], "AiMicroTool"],
  ["ai-keyword-cluster", "ai keyword cluster", "AI Keyword Clusterer", "Cluster large keyword lists into topical content hubs automatically.", ["group keywords ai", "topical cluster builder", "keyword matrix maker"], "AiMicroTool"],
  ["ai-search-intent", "ai search intent", "AI Search Intent Classifier", "Determine user search intent and SERP content format requirements.", ["classify search intent", "intent analyzer ai", "serp intent check"], "AiMicroTool"],
  ["ai-content-brief", "ai content brief", "AI Content Brief Generator", "Draft comprehensive content briefs with headings, target keywords, and word counts.", ["create content brief", "seo outline brief", "blog brief generator"], "AiMicroTool"],
  ["ai-blog-outline", "ai blog outline", "AI Blog Outline Generator", "Generate structured H2/H3 blog post outlines tailored for organic search ranking.", ["blog post outline ai", "article outline builder", "h2 h3 structure maker"], "AiMicroTool"],
  ["ai-blog-writer", "ai blog writer", "AI Blog Post Writer", "Draft well-structured, engaging long-form blog articles on any topic.", ["write blog post ai", "article draft writer", "ai content creator"], "AiMicroTool"],
  ["ai-article-rewriter", "ai article rewriter", "AI Article Rewriter", "Rewrite and refresh existing articles to improve clarity and tone.", ["rewrite blog post", "article refresh tool", "paraphrase content ai"], "AiMicroTool"],
  ["ai-product-description", "ai product description", "AI Product Description Generator", "Create persuasive product copy for e-commerce listings.", ["ecommerce product copy", "shopify description writer", "product benefits maker"], "AiMicroTool"],
  ["ai-ad-copy-generator", "ai ad copy generator", "AI Ad Copy Generator", "Generate high-converting ad headlines and body copy for paid campaigns.", ["write ad copy ai", "ppc ad headline maker", "ad campaign copy"], "AiMicroTool"],
  ["ai-facebook-ad", "ai facebook ad", "AI Facebook Ad Generator", "Draft scroll-stopping primary text and headlines for Facebook ads.", ["meta ad writer ai", "facebook campaign copy", "social ad generator"], "AiMicroTool"],
  ["ai-google-ad", "ai google ad", "AI Google Ad Generator", "Generate headlines and descriptions fitting Google Search Ad character limits.", ["google search ad copy", "responsive search ads ai", "ppc text maker"], "AiMicroTool"],
  ["ai-instagram-caption", "ai instagram caption", "AI Instagram Caption Generator", "Draft engaging Instagram captions with line breaks and call-to-actions.", ["write ig caption", "social post writer", "instagram copy generator"], "AiMicroTool"],
  ["ai-twitter-thread", "ai twitter thread", "AI Twitter Thread Generator", "Convert long articles into viral X/Twitter threads with strong hooks.", ["create twitter thread", "article to thread converter", "x thread writer"], "AiMicroTool"],
  ["ai-linkedin-post", "ai linkedin post", "AI LinkedIn Post Generator", "Draft professional LinkedIn posts that drive high engagement and comments.", ["write linkedin post", "b2b content generator", "thought leadership copy"], "AiMicroTool"],
  ["ai-youtube-script", "ai youtube script", "AI YouTube Script Writer", "Create structured video scripts with video hooks, intro, body, and CTA.", ["write youtube video script", "video content outline", "youtube video script"], "AiMicroTool"],
  ["ai-tiktok-script", "ai tiktok script", "AI TikTok Script Generator", "Generate fast-paced 30-second TikTok video scripts with visual cues.", ["tiktok script writer", "short form video script", "reels script generator"], "AiMicroTool"],
  ["ai-podcast-script", "ai podcast script", "AI Podcast Script Generator", "Write podcast episode intros, segment outlines, and sponsor read scripts.", ["podcast outline writer", "audio script generator", "podcast intro maker"], "AiMicroTool"],
  ["ai-newsletter-writer", "ai newsletter writer", "AI Newsletter Writer", "Draft catchy subject lines and engaging body copy for email newsletters.", ["write email newsletter", "newsletter copywriter", "email campaign draft"], "AiMicroTool"],

  // AI Business & Communication (51-68)
  ["ai-email-reply", "ai email reply", "AI Email Reply Generator", "Draft polite, professional email responses tailored to incoming message tone.", ["reply to email ai", "quick email responder", "professional email reply"], "AiMicroTool"],
  ["ai-cold-email", "ai cold email", "AI Cold Email Generator", "Generate personalized, high-response B2B cold sales outreach emails.", ["write cold email", "b2b sales outreach", "cold email template"], "AiMicroTool"],
  ["ai-follow-up-email", "ai follow up email", "AI Follow-up Email Generator", "Write polite follow-up emails for unanswered proposals and sales pitches.", ["sales follow up email", "meeting follow up maker", "polite check in email"], "AiMicroTool"],
  ["ai-email-subject", "ai email subject", "AI Email Subject Line Generator", "Generate high-open-rate subject lines for email campaigns.", ["email subject generator", "catchy subject lines", "open rate optimizer"], "AiMicroTool"],
  ["ai-meeting-summary", "ai meeting summary", "AI Meeting Summary Generator", "Summarize transcript notes into executive summaries and key decision points.", ["meeting notes summary", "summarize transcript ai", "executive summary maker"], "AiMicroTool"],
  ["ai-meeting-agenda", "ai meeting agenda", "AI Meeting Agenda Generator", "Draft structured meeting agendas with time allocations and discussion topics.", ["create meeting agenda", "team sync agenda", "meeting plan builder"], "AiMicroTool"],
  ["ai-action-items", "ai action items", "AI Action Items Extractor", "Extract assigned tasks, owners, and deadlines from meeting notes.", ["extract task items", "meeting action items", "todo list from notes"], "AiMicroTool"],
  ["ai-resume-builder", "ai resume builder", "AI Resume Bullet Generator", "Optimize resume bullet points using action verbs and measurable metrics.", ["resume bullet point maker", "cv bullet optimizer", "action verb resume"], "AiMicroTool"],
  ["ai-cover-letter", "ai cover letter", "AI Cover Letter Generator", "Generate tailored job cover letters matching company role descriptions.", ["write cover letter ai", "tailored cover letter", "job application letter"], "AiMicroTool"],
  ["ai-linkedin-bio", "ai linkedin bio", "AI LinkedIn Bio Generator", "Craft compelling LinkedIn headline and about section summaries.", ["linkedin headline maker", "professional bio generator", "linkedin summary ai"], "AiMicroTool"],
  ["ai-twitter-bio", "ai twitter bio", "AI Twitter Bio Generator", "Generate concise 160-character X/Twitter bio summaries.", ["x bio generator", "twitter profile bio", "short bio maker"], "AiMicroTool"],
  ["ai-instagram-bio", "ai instagram bio", "AI Instagram Bio Generator", "Create creative Instagram profile bios with line breaks and emojis.", ["ig bio creator", "instagram profile summary", "creative social bio"], "AiMicroTool"],
  ["ai-youtube-title", "ai youtube title", "AI YouTube Title Generator", "Generate high-CTR YouTube video titles that drive clicks.", ["youtube clickbait titles", "video title generator", "high ctr video title"], "AiMicroTool"],
  ["ai-hook-generator", "ai hook generator", "AI Hook Generator", "Draft powerful opening hooks for social posts, videos, and articles.", ["video opening hook", "social post hook maker", "attention grabber text"], "AiMicroTool"],
  ["ai-cta-generator", "ai cta generator", "AI Call-to-Action Generator", "Create compelling call-to-action buttons and closing phrases.", ["cta generator ai", "conversion phrase builder", "call to action maker"], "AiMicroTool"],
  ["ai-headline-generator", "ai headline generator", "AI Headline Generator", "Generate high-impact headlines based on proven copywriting formulas.", ["copywriting headline maker", "article title ideas", "attention headline maker"], "AiMicroTool"],
  ["ai-case-study", "ai case study", "AI Case Study Writer", "Structure customer success stories into Problem, Solution, and Result formats.", ["write case study ai", "customer success story", "b2b case study maker"], "AiMicroTool"],
  ["ai-whitepaper", "ai whitepaper", "AI Whitepaper Writer", "Generate authoritative whitepaper outlines and executive summaries.", ["write whitepaper ai", "b2b research report", "technical whitepaper maker"], "AiMicroTool"],

  // AI Education & Research (69-82)
  ["ai-quiz-generator", "ai quiz generator", "AI Quiz Generator", "Convert study text into multiple-choice quiz questions and answers.", ["create quiz from text", "ai test maker", "multiple choice generator"], "AiMicroTool"],
  ["ai-flashcard-generator", "ai flashcard generator", "AI Flashcard Generator", "Generate front/back flashcard study pairs from notes and textbooks.", ["create flashcards ai", "anki flashcard generator", "study card maker"], "AiMicroTool"],
  ["ai-study-guide", "ai study guide", "AI Study Guide Generator", "Transform lecture notes and topics into organized study guides.", ["create study guide ai", "exam prep notes", "lecture summary tool"], "AiMicroTool"],
  ["ai-lesson-plan", "ai lesson plan", "AI Lesson Plan Generator", "Design structured lesson plans with learning objectives and activities.", ["teacher lesson planner", "curriculum plan builder", "class activity generator"], "AiMicroTool"],
  ["ai-course-outline", "ai course outline", "AI Course Outline Generator", "Generate comprehensive multi-module online course curricula.", ["online course outline", "curriculum generator", "course syllabus builder"], "AiMicroTool"],
  ["ai-ebook-writer", "ai ebook writer", "AI Ebook Writer", "Generate multi-chapter ebook outlines and topic summaries.", ["write ebook ai", "ebook outline generator", "digital book creator"], "AiMicroTool"],
  ["ai-paper-summarizer", "ai paper summarizer", "AI Research Paper Summarizer", "Summarize complex scientific and academic research papers.", ["summarize paper ai", "academic paper summary", "research TLDR maker"], "AiMicroTool"],
  ["ai-citation-generator", "ai citation generator", "AI Citation Generator", "Format academic citations in APA, MLA, Chicago, and Harvard styles.", ["apa mla citation tool", "academic citation maker", "bibliography format"], "AiMicroTool"],
  ["ai-bibliography", "ai bibliography", "AI Bibliography Generator", "Build organized bibliographies from reference source lists.", ["create bibliography ai", "reference list builder", "works cited generator"], "AiMicroTool"],
  ["ai-plagiarism-checker", "ai plagiarism checker", "AI Plagiarism Checker", "Detect duplicate text phrases and potential source matches.", ["check plagiarism online", "originality scanner", "duplicate text detector"], "AiMicroTool"],
  ["ai-grammar-checker", "ai grammar checker", "AI Grammar Checker", "Fix grammatical errors, punctuation, and typos instantly.", ["fix grammar online", "spelling grammar checker", "proofread text ai"], "AiMicroTool"],
  ["ai-paraphrasing-tool", "ai paraphrasing tool", "AI Paraphrasing Tool", "Paraphrase sentences to improve flow, vocabulary, and conciseness.", ["paraphrase text online", "rewrite sentence ai", "reword text tool"], "AiMicroTool"],
  ["ai-tone-analyzer", "ai tone analyzer", "AI Tone Analyzer", "Analyze document sentiment tone (e.g. professional, urgent, friendly).", ["check text tone", "sentiment analysis tool", "writing tone inspector"], "AiMicroTool"],
  ["ai-sentiment-analyzer", "ai sentiment analyzer", "AI Sentiment Analyzer", "Evaluate customer reviews and feedback as Positive, Neutral, or Negative.", ["sentiment score tool", "review sentiment analysis", "customer feedback scan"], "AiMicroTool"],

  // AI Creative & Media Tools (83-100)
  ["ai-alt-text-generator", "ai alt text generator", "AI Alt Text Generator", "Generate accessible image alt text descriptions for web accessibility and SEO.", ["generate alt text ai", "image description maker", "wcag alt text tool"], "AiMicroTool"],
  ["ai-image-prompt", "ai image prompt", "AI Image Prompt Generator", "Create detailed text prompts for Midjourney, DALL-E 3, and Stable Diffusion.", ["midjourney prompt builder", "dalle prompt maker", "image generation prompt"], "AiMicroTool"],
  ["ai-thumbnail-ideas", "ai thumbnail ideas", "AI Thumbnail Idea Generator", "Brainstorm high-CTR visual thumbnail concepts for YouTube videos.", ["youtube thumbnail ideas", "video visual concepts", "thumbnail design ideas"], "AiMicroTool"],
  ["ai-meme-caption", "ai meme caption", "AI Meme Caption Generator", "Generate funny meme captions for viral social media content.", ["funny meme generator", "meme caption maker", "viral joke generator"], "AiMicroTool"],
  ["ai-story-generator", "ai story generator", "AI Story Generator", "Write creative short stories and plot outlines across genres.", ["creative story writer", "write fiction story", "plot generator ai"], "AiMicroTool"],
  ["ai-poem-generator", "ai poem generator", "AI Poem Generator", "Generate rhyming or free-verse poetry on any prompt.", ["write poem ai", "rhyme generator ai", "poetic verse builder"], "AiMicroTool"],
  ["ai-song-lyrics", "ai song lyrics", "AI Song Lyric Generator", "Draft song lyrics with verse, chorus, and bridge structures.", ["write song lyrics", "music lyric generator", "rhyming lyric maker"], "AiMicroTool"],
  ["ai-joke-generator", "ai joke generator", "AI Joke Generator", "Generate clean jokes, puns, and one-liners.", ["tell a joke ai", "pun generator online", "funny one liners"], "AiMicroTool"],
  ["ai-name-generator", "ai name generator", "AI Name Generator", "Generate creative names for characters, places, or products.", ["character name generator", "product name finder", "creative name maker"], "AiMicroTool"],
  ["ai-brand-name", "ai brand name", "AI Brand Name Generator", "Generate unique, memorable brand names for new startups.", ["startup name generator", "business name finder", "brand name maker"], "AiMicroTool"],
  ["ai-domain-name", "ai domain name", "AI Domain Name Generator", "Suggest available domain name ideas with clean keyword variations.", ["domain name finder", "available domain ideas", "website name generator"], "AiMicroTool"],
  ["ai-slogan-generator", "ai slogan generator", "AI Slogan Generator", "Draft catchy advertising slogans and brand catchphrases.", ["business slogan maker", "catchphrase generator", "advertising tagline"], "AiMicroTool"],
  ["ai-tagline-generator", "ai tagline generator", "AI Tagline Generator", "Create punchy company taglines for landing page headers.", ["company tagline maker", "brand tagline generator", "punchy header copy"], "AiMicroTool"],
  ["ai-persona-generator", "ai persona generator", "AI Persona Generator", "Create detailed target customer buyer personas for marketing strategy.", ["buyer persona maker", "target user profile", "customer persona tool"], "AiMicroTool"],
  ["ai-user-story", "ai user story", "AI User Story Generator", "Generate Agile user stories with acceptance criteria (Given/When/Then).", ["agile user story maker", "scrum user story ai", "acceptance criteria maker"], "AiMicroTool"],
  ["ai-job-description", "ai job description", "AI Job Description Generator", "Draft clear job postings with responsibilities and requirements.", ["write job posting", "job description maker", "recruitment ad generator"], "AiMicroTool"],
  ["ai-interview-questions", "ai interview questions", "AI Interview Question Generator", "Generate technical and behavioral interview questions for hiring roles.", ["technical interview questions", "candidate screening maker", "interview question generator"], "AiMicroTool"],
  ["ai-swot-analysis", "ai swot analysis", "AI SWOT Analysis Generator", "Conduct strategic SWOT analysis (Strengths, Weaknesses, Opportunities, Threats).", ["swot analysis builder", "business strategy tool", "swot matrix generator"], "AiMicroTool"]
];

const converterTools = [
  // Document Converters (1-18)
  ["pdf-to-word", "pdf to word", "PDF to Word Converter", "Convert PDF documents into editable Microsoft Word (.docx) files.", ["convert pdf docx", "pdf to doc online", "editable pdf converter"], "TextDiffChecker"],
  ["word-to-pdf", "word to pdf", "Word to PDF Converter", "Convert Word documents (.docx) into clean PDF files.", ["docx to pdf converter", "save word as pdf", "convert doc to pdf"], "TextDiffChecker"],
  ["pdf-to-excel", "pdf to excel", "PDF to Excel Converter", "Extract tables from PDF documents into Excel (.xlsx) spreadsheets.", ["convert pdf to xlsx", "pdf table to excel", "pdf spreadsheet extractor"], "JsonFormatterValidator"],
  ["excel-to-pdf", "excel to pdf", "Excel to PDF Converter", "Convert Excel spreadsheets (.xlsx) into printable PDF documents.", ["xlsx to pdf converter", "save excel as pdf", "convert spreadsheet pdf"], "JsonFormatterValidator"],
  ["pdf-to-ppt", "pdf to ppt", "PDF to PowerPoint Converter", "Convert PDF presentation slides into editable PPTX decks.", ["pdf to pptx converter", "pdf slides to powerpoint", "convert pdf presentation"], "TextDiffChecker"],
  ["ppt-to-pdf", "ppt to pdf", "PowerPoint to PDF Converter", "Convert PowerPoint slide decks (.pptx) into PDF documents.", ["pptx to pdf converter", "save slides as pdf", "convert ppt to pdf"], "TextDiffChecker"],
  ["pdf-to-image", "pdf to image", "PDF to Image Converter", "Render PDF pages into high-resolution JPG or PNG image files.", ["pdf page to png", "convert pdf to picture", "pdf image extractor"], "QrCodeGenerator"],
  ["image-to-pdf", "image to pdf", "Image to PDF Converter", "Combine JPG, PNG, and WebP images into a single PDF document.", ["convert jpg to pdf", "combine pictures to pdf", "photos to pdf maker"], "QrCodeGenerator"],
  ["pdf-to-text", "pdf to text", "PDF to Text Converter", "Extract raw text content from PDF documents.", ["extract text from pdf", "pdf text scraper", "convert pdf to txt"], "WordCounter"],
  ["text-to-pdf", "text to pdf", "Text to PDF Converter", "Convert plain text files (.txt) into formatted PDF documents.", ["txt to pdf converter", "save plain text pdf", "convert txt file"], "MarkdownEditorPreview"],
  ["pdf-merge", "pdf merge", "PDF Merge Tool", "Combine multiple PDF files into a single unified PDF document.", ["merge pdf files", "combine pdf online", "join pdf pages"], "TextDiffChecker"],
  ["pdf-split", "pdf split", "PDF Split Tool", "Extract specific pages or split PDF documents into separate files.", ["split pdf pages", "extract pdf pages", "separate pdf file"], "TextDiffChecker"],
  ["pdf-compressor", "pdf compressor", "PDF Compressor", "Reduce PDF file sizes while preserving visual text clarity.", ["compress pdf file", "reduce pdf size", "shrink pdf online"], "TextDiffChecker"],
  ["pdf-to-jpg", "pdf to jpg", "PDF to JPG Converter", "Convert PDF pages into high quality JPG image files.", ["pdf to jpg online", "extract jpg from pdf", "pdf page picture"], "QrCodeGenerator"],
  ["jpg-to-pdf", "jpg to pdf", "JPG to PDF Converter", "Convert JPG image files into printable PDF documents.", ["jpg to pdf maker", "save jpg as pdf", "picture to pdf converter"], "QrCodeGenerator"],
  ["png-to-pdf", "png to pdf", "PNG to PDF Converter", "Convert transparent or opaque PNG image files into PDF format.", ["png to pdf maker", "save png as pdf", "convert png document"], "QrCodeGenerator"],
  ["pdf-to-svg", "pdf to svg", "PDF to SVG Converter", "Convert PDF page graphics into scalable vector SVG files.", ["pdf vector to svg", "convert pdf to vector", "pdf svg converter"], "QrCodeGenerator"],
  ["svg-to-pdf", "svg to pdf", "SVG to PDF Converter", "Render scalable vector SVG graphics into print-ready PDF files.", ["svg graphic to pdf", "convert vector to pdf", "save svg pdf"], "QrCodeGenerator"],

  // Image Format Converters (19-38)
  ["png-to-jpg", "png to jpg", "PNG to JPG Converter", "Convert PNG images to compressed JPG format with custom background fill.", ["convert png to jpg", "png jpg image converter", "transparent png to jpg"], "QrCodeGenerator"],
  ["jpg-to-png", "jpg to png", "JPG to PNG Converter", "Convert JPG photos to PNG format.", ["convert jpg to png", "jpg png image converter", "save jpg as png"], "QrCodeGenerator"],
  ["png-to-webp", "png to webp", "PNG to WebP Converter", "Convert PNG images into lightweight WebP image files for faster page load.", ["convert png to webp", "webp image optimizer", "compress image webp"], "QrCodeGenerator"],
  ["webp-to-png", "webp to png", "WebP to PNG Converter", "Convert modern WebP images back into widely compatible PNG files.", ["convert webp to png", "webp file decoder", "save webp as png"], "QrCodeGenerator"],
  ["png-to-svg", "png to svg", "PNG to SVG Vector Converter", "Trace and convert PNG raster graphics into scalable SVG vector shapes.", ["raster to vector svg", "convert image to vector", "png vectorizer"], "QrCodeGenerator"],
  ["svg-to-png", "svg to png", "SVG to PNG Converter", "Render SVG vector files into high-resolution PNG image rasters.", ["convert svg to png", "export svg picture", "svg rasterizer"], "QrCodeGenerator"],
  ["jpg-to-webp", "jpg to webp", "JPG to WebP Converter", "Compress JPG photos into modern WebP web format.", ["convert jpg to webp", "optimize photos webp", "jpg webp converter"], "QrCodeGenerator"],
  ["webp-to-jpg", "webp to jpg", "WebP to JPG Converter", "Convert WebP images to standard JPG image format.", ["convert webp to jpg", "webp image decoder", "save webp as jpg"], "QrCodeGenerator"],
  ["heic-to-jpg", "heic to jpg", "HEIC to JPG Converter", "Convert iPhone HEIC photos into universally supported JPG images.", ["iphone photo converter", "convert heic picture", "heic to jpg online"], "QrCodeGenerator"],
  ["jpg-to-heic", "jpg to heic", "JPG to HEIC Converter", "Convert JPG images into high-efficiency HEIC photos.", ["convert jpg to heic", "create heic file", "heic photo maker"], "QrCodeGenerator"],
  ["avif-to-jpg", "avif to jpg", "AVIF to JPG Converter", "Convert modern AVIF image files into compatible JPG format.", ["convert avif to jpg", "avif image decoder", "save avif as jpg"], "QrCodeGenerator"],
  ["jpg-to-avif", "jpg to avif", "JPG to AVIF Converter", "Convert JPG photos into ultra-compressed AVIF images.", ["convert jpg to avif", "avif image compressor", "optimize image avif"], "QrCodeGenerator"],
  ["bmp-to-jpg", "bmp to jpg", "BMP to JPG Converter", "Convert bitmap images (.bmp) into compressed JPG files.", ["convert bmp to jpg", "bitmap image converter", "bmp compressed photo"], "QrCodeGenerator"],
  ["jpg-to-bmp", "jpg to bmp", "JPG to BMP Converter", "Convert JPG compressed photos into uncompressed BMP bitmaps.", ["convert jpg to bmp", "create bitmap file", "save photo bmp"], "QrCodeGenerator"],
  ["tiff-to-jpg", "tiff to jpg", "TIFF to JPG Converter", "Convert multi-page or single TIFF images into standard JPG files.", ["convert tiff to jpg", "tiff picture converter", "save tiff jpg"], "QrCodeGenerator"],
  ["gif-to-png", "gif to png", "GIF to PNG Converter", "Extract frames or convert animated GIF images into static PNG files.", ["convert gif to png", "extract gif frame", "static png from gif"], "QrCodeGenerator"],
  ["png-to-gif", "png to gif", "PNG to GIF Converter", "Convert PNG images into static or looping GIF files.", ["convert png to gif", "create gif from png", "png image gif"], "QrCodeGenerator"],
  ["ico-to-png", "ico to png", "ICO to PNG Converter", "Convert Windows ICO favicon icons into high-res PNG pictures.", ["convert ico to png", "favicon to picture", "extract ico png"], "QrCodeGenerator"],
  ["png-to-ico", "png to ico", "PNG to ICO Favicon Converter", "Convert PNG graphics into ICO favicon files for websites.", ["create ico favicon", "png to ico converter", "make website icon"], "QrCodeGenerator"],
  ["eps-to-svg", "eps to svg", "EPS to SVG Converter", "Convert PostScript EPS vector files into clean web SVG files.", ["convert eps to svg", "vector eps converter", "eps graphic to svg"], "QrCodeGenerator"],

  // Video & Audio Converters (39-52)
  ["mp4-to-mp3", "mp4 to mp3", "MP4 to MP3 Audio Extractor", "Extract high quality MP3 audio tracks from MP4 video files.", ["extract audio from video", "convert mp4 audio", "mp4 sound extractor"], "Base64JwtDecoder"],
  ["mp3-to-wav", "mp3 to wav", "MP3 to WAV Converter", "Convert compressed MP3 audio files into uncompressed WAV audio.", ["convert mp3 to wav", "mp3 wav decoder", "save mp3 as wav"], "Base64JwtDecoder"],
  ["wav-to-mp3", "wav to mp3", "WAV to MP3 Converter", "Compress large WAV audio recordings into portable MP3 files.", ["compress wav file", "convert wav to mp3", "wav audio compressor"], "Base64JwtDecoder"],
  ["webm-to-mp4", "webm to mp4", "WebM to MP4 Converter", "Convert HTML5 WebM videos into universally supported MP4 files.", ["convert webm to mp4", "webm video decoder", "save webm as mp4"], "Base64JwtDecoder"],
  ["mp4-to-webm", "mp4 to webm", "MP4 to WebM Converter", "Convert MP4 videos into HTML5 WebM format for web streaming.", ["convert mp4 to webm", "web video compressor", "mp4 webm maker"], "Base64JwtDecoder"],
  ["mov-to-mp4", "mov to mp4", "MOV to MP4 Converter", "Convert QuickTime MOV videos into standard MP4 video format.", ["quicktime to mp4", "convert mov video", "iphone video to mp4"], "Base64JwtDecoder"],
  ["avi-to-mp4", "avi to mp4", "AVI to MP4 Converter", "Convert legacy AVI video files into modern compressed MP4 videos.", ["convert avi to mp4", "avi video converter", "save avi as mp4"], "Base64JwtDecoder"],
  ["mkv-to-mp4", "mkv to mp4", "MKV to MP4 Converter", "Convert Matroska MKV video files into compatible MP4 format.", ["convert mkv to mp4", "mkv video converter", "remux mkv to mp4"], "Base64JwtDecoder"],
  ["flv-to-mp4", "flv to mp4", "FLV to MP4 Converter", "Convert Flash Video FLV files into modern MP4 videos.", ["convert flv to mp4", "flash video converter", "save flv as mp4"], "Base64JwtDecoder"],
  ["ogg-to-mp3", "ogg to mp3", "OGG to MP3 Converter", "Convert OGG Vorbis audio files into standard MP3 audio.", ["convert ogg to mp3", "ogg audio decoder", "save ogg as mp3"], "Base64JwtDecoder"],
  ["flac-to-mp3", "flac to mp3", "FLAC to MP3 Converter", "Compress lossless FLAC audio files into compact MP3 tracks.", ["convert flac to mp3", "flac audio compressor", "save flac as mp3"], "Base64JwtDecoder"],
  ["aac-to-mp3", "aac to mp3", "AAC to MP3 Converter", "Convert AAC audio tracks into compatible MP3 files.", ["convert aac to mp3", "aac audio decoder", "save aac as mp3"], "Base64JwtDecoder"],
  ["m4a-to-mp3", "m4a to mp3", "M4A to MP3 Converter", "Convert Apple M4A voice memos and audio into MP3 format.", ["convert m4a to mp3", "apple audio converter", "m4a audio decoder"], "Base64JwtDecoder"],
  ["video-to-gif", "video to gif", "Video to GIF Converter", "Convert video clips into looping animated GIF images.", ["make gif from video", "mp4 to animated gif", "clip to gif maker"], "QrCodeGenerator"],

  // Unit Converters (53-75)
  ["length-converter", "length converter", "Length Converter", "Convert length units across meters, feet, inches, kilometers, and miles.", ["meters to feet", "inches to cm", "distance unit converter"], "CaseConverter"],
  ["weight-converter", "weight converter", "Weight & Mass Converter", "Convert mass units across kilograms, pounds, ounces, and grams.", ["kg to lbs", "lbs to kg", "mass unit converter"], "CaseConverter"],
  ["temperature-converter", "temperature converter", "Temperature Converter", "Convert temperature values between Celsius, Fahrenheit, and Kelvin.", ["celsius to fahrenheit", "fahrenheit to celsius", "temp scale converter"], "CaseConverter"],
  ["volume-converter", "volume converter", "Volume Converter", "Convert volume measures across liters, gallons, milliliters, and fluid ounces.", ["liters to gallons", "ml to oz", "liquid volume converter"], "CaseConverter"],
  ["area-converter", "area converter", "Area Converter", "Convert square meters, square feet, acres, and hectares.", ["sq ft to sq meters", "acres to hectares", "land area converter"], "CaseConverter"],
  ["speed-converter", "speed converter", "Speed Converter", "Convert speed values across km/h, mph, meters/sec, and knots.", ["kmh to mph", "mph to kmh", "velocity converter"], "CaseConverter"],
  ["time-converter", "time converter", "Time Duration Converter", "Convert time units across seconds, minutes, hours, days, and weeks.", ["hours to minutes", "seconds to hours", "time unit calculator"], "UnixTimestampConverter"],
  ["data-storage-converter", "data storage converter", "Data Storage Converter", "Convert data storage units across Bytes, KB, MB, GB, TB, and PB.", ["mb to gb converter", "bytes to megabytes", "digital storage calculator"], "CaseConverter"],
  ["energy-converter", "energy converter", "Energy Converter", "Convert energy units across Joules, Kilojoules, Calories, and Kilowatt-hours.", ["joules to calories", "kwh to joules", "energy unit tool"], "CaseConverter"],
  ["power-converter", "power converter", "Power Converter", "Convert power units across Watts, Kilowatts, and Horsepower.", ["watts to horsepower", "kw to hp", "power unit calculator"], "CaseConverter"],
  ["pressure-converter", "pressure converter", "Pressure Converter", "Convert pressure units across PSI, Bar, Pascals, and Atmospheres.", ["psi to bar", "pascals to psi", "pressure unit tool"], "CaseConverter"],
  ["force-converter", "force converter", "Force Converter", "Convert force units across Newtons, Kilonewtons, and Pound-force.", ["newtons to lbs force", "force unit calculator", "kn to newtons"], "CaseConverter"],
  ["torque-converter", "torque converter", "Torque Converter", "Convert torque units across Newton-meters and Foot-pounds.", ["nm to ft lbs", "torque unit calculator", "foot pounds to nm"], "CaseConverter"],
  ["angle-converter", "angle converter", "Angle Converter", "Convert angular units between Degrees, Radians, and Gradians.", ["degrees to radians", "radians to degrees", "angle unit tool"], "CaseConverter"],
  ["fuel-efficiency-converter", "fuel efficiency converter", "Fuel Efficiency Converter", "Convert fuel economy values between MPG and L/100km.", ["mpg to l 100km", "fuel consumption converter", "gas mileage calculator"], "CaseConverter"],
  ["frequency-converter", "frequency converter", "Frequency Converter", "Convert frequency units across Hertz, Kilohertz, Megahertz, and Gigahertz.", ["hz to khz", "mhz to ghz", "frequency unit tool"], "CaseConverter"],
  ["density-converter", "density converter", "Density Converter", "Convert mass density values across kg/m³, g/cm³, and lbs/ft³.", ["kg m3 to g cm3", "density unit tool", "mass volume density"], "CaseConverter"],
  ["flow-rate-converter", "flow rate converter", "Flow Rate Converter", "Convert fluid flow rates across liters/sec, gallons/min, and m³/hour.", ["gpm to lps", "fluid flow rate", "flow volume calculator"], "CaseConverter"],
  ["viscosity-converter", "viscosity converter", "Viscosity Converter", "Convert dynamic and kinematic viscosity values.", ["pascal seconds to poise", "viscosity unit converter", "fluid friction tool"], "CaseConverter"],
  ["cooking-converter", "cooking converter", "Cooking Measurement Converter", "Convert kitchen recipe units across cups, tablespoons, teaspoons, and grams.", ["cups to grams", "tbsp to tsp", "recipe unit converter"], "CaseConverter"],
  ["shoe-size-converter", "shoe size converter", "Shoe Size Converter", "Convert international shoe sizes across US, UK, EU, and CM measurements.", ["us to eu shoe size", "uk to us shoe size", "international shoe converter"], "CaseConverter"],
  ["clothing-size-converter", "clothing size converter", "Clothing Size Converter", "Convert apparel measurements across US, UK, EU, and Asian sizing scales.", ["us to eu clothes size", "international clothing size", "apparel size tool"], "CaseConverter"],

  // Financial & Number Converters (76-88)
  ["currency-converter", "currency converter", "Currency Converter", "Convert foreign exchange rates across USD, EUR, GBP, JPY, and INR.", ["usd to eur converter", "foreign exchange rates", "currency calculator"], "CaseConverter"],
  ["number-to-words", "number to words", "Number to Words Converter", "Convert numeric dollar and currency amounts into written English word sentences.", ["number to words tool", "write check amount", "amount in words"], "WordCounter"],
  ["words-to-number", "words to number", "Words to Number Converter", "Convert written English number phrases back into numeric digit values.", ["text to digits", "words to number tool", "parse written numbers"], "WordCounter"],
  ["roman-numeral-converter", "roman numeral converter", "Roman Numeral Converter", "Convert numbers to Roman numerals (e.g. 2026 -> MMXXVI) and vice versa.", ["number to roman numerals", "decode roman numerals", "roman numeral maker"], "CaseConverter"],
  ["binary-to-decimal", "binary to decimal", "Binary to Decimal Converter", "Convert binary base-2 strings into decimal base-10 integers.", ["binary base 2 to 10", "decode binary digits", "binary integer converter"], "Base64JwtDecoder"],
  ["decimal-to-binary", "decimal to binary", "Decimal to Binary Converter", "Convert decimal integers into binary 0s and 1s.", ["decimal to base 2", "convert number binary", "decimal binary tool"], "Base64JwtDecoder"],
  ["hex-to-decimal", "hex to decimal", "Hexadecimal to Decimal Converter", "Convert hexadecimal base-16 strings into decimal integers.", ["hex to base 10", "decode hex number", "hexadecimal converter"], "Base64JwtDecoder"],
  ["decimal-to-hex", "decimal to hex", "Decimal to Hexadecimal Converter", "Convert decimal numbers into hexadecimal strings.", ["decimal to base 16", "convert number hex", "decimal hex tool"], "Base64JwtDecoder"],
  ["octal-to-decimal", "octal to decimal", "Octal to Decimal Converter", "Convert octal base-8 numbers into decimal values.", ["octal to base 10", "decode octal number", "octal integer converter"], "Base64JwtDecoder"],
  ["decimal-to-octal", "decimal to octal", "Decimal to Octal Converter", "Convert decimal numbers into octal base-8 strings.", ["decimal to base 8", "convert number octal", "decimal octal tool"], "Base64JwtDecoder"],
  ["fraction-to-decimal", "fraction to decimal", "Fraction to Decimal Converter", "Convert mathematical fractions (e.g., 3/4) into decimal values (0.75).", ["fraction to decimal tool", "3 4 to decimal", "math fraction converter"], "CaseConverter"],
  ["decimal-to-fraction", "decimal to fraction", "Decimal to Fraction Converter", "Convert decimal numbers into simplified fractions.", ["decimal to fraction tool", "0.75 to fraction", "simplify decimal fraction"], "CaseConverter"],
  ["percentage-converter", "percentage converter", "Percentage Calculator", "Calculate percentage increases, decreases, discounts, and margin ratios.", ["percentage change tool", "discount percentage calculator", "percent ratio tool"], "CaseConverter"],

  // Location & Time Converters (89-100)
  ["timezone-converter", "timezone converter", "Timezone Converter", "Convert dates and meeting times across global world timezones.", ["world time converter", "pst to est converter", "gmt time tool"], "UnixTimestampConverter"],
  ["gps-coordinates-converter", "gps coordinates converter", "GPS Coordinates Converter", "Convert GPS coordinates between Decimal Degrees, DMS, and UTM.", ["gps coordinate tool", "latitude longitude format", "map coordinate converter"], "UrlSlugUtmBuilder"],
  ["lat-long-converter", "lat long converter", "Latitude Longitude Converter", "Convert address locations into latitude and longitude geographic coordinates.", ["address to lat long", "find lat long coordinates", "geo location converter"], "UrlSlugUtmBuilder"],
  ["dms-to-decimal", "dms to decimal", "DMS to Decimal Degrees Converter", "Convert Degrees, Minutes, and Seconds into decimal degree coordinates.", ["dms to lat long", "convert dms decimal", "degrees minutes seconds tool"], "UrlSlugUtmBuilder"],
  ["decimal-to-dms", "decimal to dms", "Decimal Degrees to DMS Converter", "Convert decimal degree coordinates into Degrees, Minutes, and Seconds format.", ["decimal to dms tool", "convert lat long dms", "decimal degrees minutes"], "UrlSlugUtmBuilder"],
  ["utm-converter", "utm converter", "UTM Coordinate Converter", "Convert Universal Transverse Mercator (UTM) coordinates to latitude/longitude.", ["utm to lat long", "utm zone converter", "map grid converter"], "UrlSlugUtmBuilder"],
  ["date-format-converter", "date format converter", "Date Format Converter", "Reformat dates across YYYY-MM-DD, MM/DD/YYYY, and custom date patterns.", ["reformat date string", "change date layout", "date string parser"], "UnixTimestampConverter"],
  ["calendar-converter", "calendar converter", "Calendar System Converter", "Convert dates across Gregorian, Julian, Islamic, and Hebrew calendar systems.", ["gregorian to hijri", "calendar converter tool", "julian to gregorian"], "UnixTimestampConverter"],
  ["julian-date-converter", "julian date converter", "Julian Date Converter", "Convert standard calendar dates to Julian Day Numbers (JDN).", ["calendar to julian day", "julian day number tool", "astronomy date tool"], "UnixTimestampConverter"],
  ["unix-time-converter", "unix time converter", "Unix Time Converter", "Convert Unix timestamps to human readable dates.", ["unix time to date", "convert timestamp date", "epoch time parser"], "UnixTimestampConverter"],
  ["excel-date-converter", "excel date converter", "Excel Serial Date Converter", "Convert Excel serial date numbers (e.g. 45000) to ISO dates.", ["excel serial date tool", "convert excel serial date", "excel date serial"], "UnixTimestampConverter"],
  ["leap-year-calculator", "leap year calculator", "Leap Year Calculator", "Determine whether any given year is a leap year with rule explanations.", ["check leap year", "is leap year", "leap year calendar tool"], "UnixTimestampConverter"],
  ["week-number-calculator", "week number calculator", "ISO Week Number Calculator", "Determine ISO week numbers and day of the year for target calendar dates.", ["find week number", "iso week number tool", "day of year calculator"], "UnixTimestampConverter"]
];

function buildSeedItems(list, categoryId) {
  return list.map(item => {
    const [slug, pillarKeyword, title, description, supportingKeywords, toolComponent] = item;
    return {
      slug,
      cluster: categoryId,
      title: `${title} | Free Online Tool`,
      description,
      pillarKeyword,
      supportingKeywords,
      toolComponent
    };
  });
}

const allSeedItems = [
  ...buildSeedItems(seoTools, "seo-tools"),
  ...buildSeedItems(developerTools, "developer-tools"),
  ...buildSeedItems(aiTools, "ai-tools"),
  ...buildSeedItems(converterTools, "converters")
];

console.log("Total seed items count:", allSeedItems.length);

const targetPath = path.join(__dirname, 'tools-seed.json');
fs.writeFileSync(targetPath, JSON.stringify(allSeedItems, null, 2), 'utf8');
console.log(`Successfully generated tools-seed.json at ${targetPath} with ${allSeedItems.length} items.`);
