import type { LocalEngine, StudioResult } from "./types";

type EngineOutput = Omit<StudioResult, "id" | "createdAt" | "processing">;
const output = (engineId: string, title: string, content: string, extension = "txt", mimeType = "text/plain"): EngineOutput => ({ engineId, title, content, extension, mimeType });
const json = (engineId: string, title: string, value: unknown): EngineOutput => output(engineId, title, JSON.stringify(value, null, 2), "json", "application/json");
const lines = (input: string) => input.replace(/\r\n?/g, "\n").split("\n");
const numbers = (input: string) => input.trim().split(/[\s,]+/).filter(Boolean).map(Number);
const requireFiniteNumbers = (input: string) => { const values = numbers(input); if (!values.length || values.some((value) => !Number.isFinite(value))) throw new Error("Enter one or more finite numbers."); return values; };
const parseJson = (input: string): unknown => JSON.parse(input);
const isObject = (value: unknown): value is Record<string, unknown> => value !== null && typeof value === "object" && !Array.isArray(value);
const parseCountAndBody = (input: string) => { const [first, ...rest] = lines(input); const count = Number.parseInt(first, 10); if (!Number.isSafeInteger(count) || count < 0) throw new Error("The first line must be a non-negative integer."); return { count, body: rest.join("\n") }; };

function wordTokens(input: string): string[] { return input.toLowerCase().match(/[\p{L}\p{N}_'-]+/gu) ?? []; }
function frequency(values: string[]): Record<string, number> { const result: Record<string, number> = {}; for (const value of values) result[value] = (result[value] ?? 0) + 1; return result; }
function uniqueJson(values: unknown[]): unknown[] { const seen = new Set<string>(); return values.filter((value) => { const key = JSON.stringify(value); if (seen.has(key)) return false; seen.add(key); return true; }); }
function jsonDepth(value: unknown): number { if (Array.isArray(value)) return value.length ? 1 + Math.max(...value.map(jsonDepth)) : 1; if (isObject(value)) { const children = Object.values(value); return children.length ? 1 + Math.max(...children.map(jsonDepth)) : 1; } return 0; }
function pointerGet(value: unknown, pointer: string): unknown { if (pointer === "") return value; if (!pointer.startsWith("/")) throw new Error("JSON Pointer must be empty or start with /."); return pointer.slice(1).split("/").reduce<unknown>((current, token) => { const key = token.replace(/~1/g, "/").replace(/~0/g, "~"); if (Array.isArray(current)) { const index = Number(key); if (!Number.isSafeInteger(index) || index < 0 || index >= current.length) throw new Error(`JSON Pointer segment not found: ${key}`); return current[index]; } if (isObject(current) && Object.hasOwn(current, key)) return current[key]; throw new Error(`JSON Pointer segment not found: ${key}`); }, value); }
function quoteCsv(value: string): string { return `"${value.replace(/"/g, '""')}"`; }
function parseCsvRow(row: string): string[] { const cells: string[] = []; let cell = ""; let quoted = false; for (let i = 0; i < row.length; i++) { const char = row[i]; if (char === '"') { if (quoted && row[i + 1] === '"') { cell += '"'; i++; } else quoted = !quoted; } else if (char === "," && !quoted) { cells.push(cell); cell = ""; } else cell += char; } if (quoted) throw new Error("Unclosed quoted CSV field."); cells.push(cell); return cells; }
function gcd(a: bigint, b: bigint): bigint { a = a < 0n ? -a : a; b = b < 0n ? -b : b; while (b) [a, b] = [b, a % b]; return a; }
function integerPair(input: string): [bigint, bigint] { const parts = input.trim().split(/\s+/); if (parts.length !== 2 || parts.some((part) => !/^-?\d+$/.test(part))) throw new Error("Enter exactly two integers."); return [BigInt(parts[0]), BigInt(parts[1])]; }
function isPrime(value: bigint): boolean { if (value < 2n) return false; if (value % 2n === 0n) return value === 2n; for (let divisor = 3n; divisor * divisor <= value; divisor += 2n) if (value % divisor === 0n) return false; return true; }
function romanEncode(value: number): string { if (!Number.isInteger(value) || value < 1 || value > 3999) throw new Error("Roman numeral input must be an integer from 1 to 3999."); const map: Array<[number, string]> = [[1000,"M"],[900,"CM"],[500,"D"],[400,"CD"],[100,"C"],[90,"XC"],[50,"L"],[40,"XL"],[10,"X"],[9,"IX"],[5,"V"],[4,"IV"],[1,"I"]]; let result = ""; for (const [amount, symbol] of map) while (value >= amount) { result += symbol; value -= amount; } return result; }
function romanDecode(input: string): number { const text = input.trim().toUpperCase(); if (!/^(?=[MDCLXVI])M{0,3}(CM|CD|D?C{0,3})(XC|XL|L?X{0,3})(IX|IV|V?I{0,3})$/.test(text)) throw new Error("Enter a canonical Roman numeral from I to MMMCMXCIX."); const values: Record<string, number> = { I:1,V:5,X:10,L:50,C:100,D:500,M:1000 }; let total = 0; for (let i=0;i<text.length;i++) total += values[text[i]] < (values[text[i+1]] ?? 0) ? -values[text[i]] : values[text[i]]; return total; }
function crc32(input: string): string { let crc = 0xffffffff; for (const byte of new TextEncoder().encode(input)) { crc ^= byte; for (let bit=0;bit<8;bit++) crc = (crc >>> 1) ^ (crc & 1 ? 0xedb88320 : 0); } return ((crc ^ 0xffffffff) >>> 0).toString(16).padStart(8,"0"); }
function isoWeek(date: Date): { year: number; week: number } { const copy = new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate())); const day = copy.getUTCDay() || 7; copy.setUTCDate(copy.getUTCDate() + 4 - day); const yearStart = new Date(Date.UTC(copy.getUTCFullYear(),0,1)); return { year: copy.getUTCFullYear(), week: Math.ceil((((copy.getTime()-yearStart.getTime())/86400000)+1)/7) }; }

export function runBatch4Engine(engineId: string, input: string): EngineOutput {
  switch (engineId) {
    case "character-count": return json(engineId, "Character counts", { utf16Units: input.length, codePoints: [...input].length });
    case "code-point-count": return output(engineId, "Unicode code point count", String([...input].length));
    case "grapheme-count": return output(engineId, "Grapheme count", String([...new Intl.Segmenter(undefined,{granularity:"grapheme"}).segment(input)].length));
    case "word-count": return output(engineId, "Word count", String(wordTokens(input).length));
    case "sentence-count": return output(engineId, "Sentence count", String((input.match(/[^.!?]+[.!?]+(?:\s|$)|[^.!?\s][^.!?]*$/g) ?? []).length));
    case "paragraph-count": return output(engineId, "Paragraph count", String(input.trim() ? input.trim().split(/(?:\r?\n){2,}/).filter((item)=>item.trim()).length : 0));
    case "character-frequency": return json(engineId, "Character frequency", frequency([...input]));
    case "word-frequency": return json(engineId, "Word frequency", frequency(wordTokens(input)));
    case "reverse-text": return output(engineId, "Reversed code points", [...input].reverse().join(""));
    case "reverse-words": return output(engineId, "Reversed word order", input.trim().split(/\s+/).reverse().join(" "));
    case "trim-lines": return output(engineId, "Trimmed lines", lines(input).map((line)=>line.trim()).join("\n"));
    case "prefix-lines": { const [prefix,...body]=lines(input); return output(engineId,"Prefixed lines",body.map((line)=>prefix+line).join("\n")); }
    case "suffix-lines": { const [suffix,...body]=lines(input); return output(engineId,"Suffixed lines",body.map((line)=>line+suffix).join("\n")); }
    case "number-lines": return output(engineId,"Numbered lines",lines(input).map((line,index)=>`${index+1}. ${line}`).join("\n"));
    case "filter-lines": { const [query,...body]=lines(input); return output(engineId,"Matching lines",body.filter((line)=>line.includes(query)).join("\n")); }
    case "remove-matching-lines": { const [query,...body]=lines(input); return output(engineId,"Non-matching lines",body.filter((line)=>!line.includes(query)).join("\n")); }
    case "repeat-text": { const {count,body}=parseCountAndBody(input); if(count>1000)throw new Error("Repeat count cannot exceed 1000."); return output(engineId,"Repeated text",Array.from({length:count},()=>body).join("")); }
    case "truncate-text": { const {count,body}=parseCountAndBody(input); return output(engineId,"Truncated text",[...body].slice(0,count).join("")); }
    case "tabs-to-spaces": { const {count,body}=parseCountAndBody(input); if(count<1||count>16)throw new Error("Tab width must be from 1 to 16."); return output(engineId,"Spaces result",body.replace(/\t/g," ".repeat(count))); }
    case "spaces-to-tabs": { const {count,body}=parseCountAndBody(input); if(count<1||count>16)throw new Error("Indent width must be from 1 to 16."); const pattern=new RegExp(`^(?: {${count}})+`,`gm`); return output(engineId,"Tabs result",body.replace(pattern,(match)=>"\t".repeat(match.length/count))); }
    case "json-validate": { parseJson(input); return output(engineId,"JSON validation","Valid JSON"); }
    case "json-value-type": { const value=parseJson(input); return output(engineId,"JSON value type",value===null?"null":Array.isArray(value)?"array":typeof value); }
    case "json-object-keys": { const value=parseJson(input); if(!isObject(value))throw new Error("Top-level JSON value must be an object."); return json(engineId,"Object keys",Object.keys(value)); }
    case "json-array-length": { const value=parseJson(input); if(!Array.isArray(value))throw new Error("Top-level JSON value must be an array."); return output(engineId,"Array length",String(value.length)); }
    case "json-pointer-get": { const [pointer,...body]=lines(input); return json(engineId,"JSON Pointer result",pointerGet(parseJson(body.join("\n")),pointer)); }
    case "json-array-dedupe": { const value=parseJson(input); if(!Array.isArray(value))throw new Error("Top-level JSON value must be an array."); return json(engineId,"Deduplicated JSON array",uniqueJson(value)); }
    case "json-array-sort": { const value=parseJson(input); if(!Array.isArray(value)||value.some((item)=>!["string","number"].includes(typeof item)))throw new Error("Array must contain only strings or only numbers."); if(value.some((item)=>typeof item!==typeof value[0]))throw new Error("Array values must share one type."); return json(engineId,"Sorted JSON array",[...value].sort((a,b)=>typeof a==="number"?(a as number)-(b as number):String(a).localeCompare(String(b)))); }
    case "json-string-escape": return output(engineId,"JSON string literal",JSON.stringify(input));
    case "json-string-unescape": { const value=parseJson(input); if(typeof value!=="string")throw new Error("Input must be one valid JSON string literal."); return output(engineId,"Unescaped JSON string",value); }
    case "json-lines-to-array": return json(engineId,"JSON Lines array",lines(input).filter((line)=>line.trim()).map(parseJson));
    case "json-array-to-lines": { const value=parseJson(input); if(!Array.isArray(value))throw new Error("Top-level JSON value must be an array."); return output(engineId,"JSON Lines",value.map((item)=>JSON.stringify(item)).join("\n"),"jsonl","application/x-ndjson"); }
    case "json-depth": return output(engineId,"JSON depth",String(jsonDepth(parseJson(input))));
    case "url-parse": { const url=new URL(input.trim()); return json(engineId,"Parsed URL",{protocol:url.protocol,username:url.username,password:url.password?"[present]":"",hostname:url.hostname,port:url.port,pathname:url.pathname,search:url.search,hash:url.hash}); }
    case "url-origin": return output(engineId,"URL origin",new URL(input.trim()).origin);
    case "url-path-segments": return json(engineId,"URL path segments",new URL(input.trim()).pathname.split("/").filter(Boolean).map(decodeURIComponent));
    case "url-query-build": { const params=new URLSearchParams(); for(const line of lines(input).filter(Boolean)){const index=line.indexOf("="); params.append(index<0?line:line.slice(0,index),index<0?"":line.slice(index+1));} return output(engineId,"Built query string",params.toString()); }
    case "url-query-sort": { const params=new URLSearchParams(input.trim().replace(/^\?/,"")); params.sort(); return output(engineId,"Sorted query string",params.toString()); }
    case "url-normalize": { const url=new URL(input.trim()); url.hash=""; url.hostname=url.hostname.toLowerCase(); if((url.protocol==="http:"&&url.port==="80")||(url.protocol==="https:"&&url.port==="443"))url.port=""; return output(engineId,"Normalized URL",url.toString()); }
    case "url-resolve": { const [base,relative]=lines(input); if(!base||relative===undefined)throw new Error("Enter the base URL on line one and the relative reference on line two."); return output(engineId,"Resolved URL",new URL(relative,base).toString()); }
    case "data-url-encode": return output(engineId,"Text data URL",`data:text/plain;charset=utf-8,${encodeURIComponent(input)}`);
    case "data-url-decode": { const match=input.trim().match(/^data:([^,]*),(.*)$/s); if(!match||/;base64/i.test(match[1]))throw new Error("Enter a non-Base64 percent-encoded data URL."); return output(engineId,"Decoded data URL",decodeURIComponent(match[2])); }
    case "domain-extract": return output(engineId,"Hostname",new URL(input.trim()).hostname);
    case "gcd": { const [a,b]=integerPair(input); return output(engineId,"Greatest common divisor",gcd(a,b).toString()); }
    case "lcm": { const [a,b]=integerPair(input); return output(engineId,"Least common multiple",a===0n||b===0n?"0":((a/gcd(a,b))*b<0n?-(a/gcd(a,b))*b:(a/gcd(a,b))*b).toString()); }
    case "prime-check": { if(!/^-?\d+$/.test(input.trim()))throw new Error("Enter one integer."); return output(engineId,"Prime check",String(isPrime(BigInt(input.trim())))); }
    case "integer-factors": { if(!/^\d+$/.test(input.trim()))throw new Error("Enter one positive integer."); const value=BigInt(input.trim()); if(value<1n||value>1000000000000n)throw new Error("Input must be from 1 to 1,000,000,000,000."); const factors: bigint[]=[]; for(let i=1n;i*i<=value;i++)if(value%i===0n){factors.push(i);if(i*i!==value)factors.push(value/i);} return output(engineId,"Integer factors",factors.sort((a,b)=>a<b?-1:1).join("\n")); }
    case "mean": { const values=requireFiniteNumbers(input); return output(engineId,"Arithmetic mean",String(values.reduce((a,b)=>a+b,0)/values.length)); }
    case "median": { const values=[...requireFiniteNumbers(input)].sort((a,b)=>a-b); const middle=Math.floor(values.length/2); return output(engineId,"Median",String(values.length%2?values[middle]:(values[middle-1]+values[middle])/2)); }
    case "number-minmax": { const values=requireFiniteNumbers(input); return json(engineId,"Minimum and maximum",{minimum:Math.min(...values),maximum:Math.max(...values)}); }
    case "number-sort": return output(engineId,"Sorted numbers",[...requireFiniteNumbers(input)].sort((a,b)=>a-b).join("\n"));
    case "percentage": { const [part,total]=requireFiniteNumbers(input); if(total===undefined||requireFiniteNumbers(input).length!==2||total===0)throw new Error("Enter part and non-zero total."); return output(engineId,"Percentage",String((part/total)*100)); }
    case "byte-format": { const value=Number(input.trim()); if(!Number.isFinite(value)||value<0)throw new Error("Enter a non-negative byte count."); const units=["B","KiB","MiB","GiB","TiB","PiB"]; let amount=value,index=0; while(amount>=1024&&index<units.length-1){amount/=1024;index++;} return output(engineId,"Formatted bytes",`${Number(amount.toFixed(2))} ${units[index]}`); }
    case "roman-encode": return output(engineId,"Roman numeral",romanEncode(Number(input.trim())));
    case "roman-decode": return output(engineId,"Decimal integer",String(romanDecode(input)));
    case "date-difference": { const [start,end]=lines(input).map(Date.parse); if(!Number.isFinite(start)||!Number.isFinite(end))throw new Error("Enter two parseable date-times on separate lines."); return json(engineId,"Date difference",{milliseconds:end-start,seconds:(end-start)/1000,days:(end-start)/86400000}); }
    case "date-add-days": { const [dateText,daysText]=lines(input); const date=new Date(dateText); const days=Number(daysText); if(Number.isNaN(date.getTime())||!Number.isFinite(days))throw new Error("Enter an ISO date-time and a finite day count on separate lines."); date.setUTCDate(date.getUTCDate()+days); return output(engineId,"Adjusted date",date.toISOString()); }
    case "day-of-week": { const date=new Date(input.trim()); if(Number.isNaN(date.getTime()))throw new Error("Enter a parseable date-time."); return output(engineId,"UTC day of week",["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"][date.getUTCDay()]); }
    case "leap-year": { const year=Number(input.trim()); if(!Number.isInteger(year))throw new Error("Enter an integer year."); return output(engineId,"Leap year check",String(year%4===0&&(year%100!==0||year%400===0))); }
    case "iso-week": { const date=new Date(input.trim()); if(Number.isNaN(date.getTime()))throw new Error("Enter a parseable date-time."); return json(engineId,"ISO week",isoWeek(date)); }
    case "tsv-to-csv": return output(engineId,"CSV result",lines(input).map((line)=>line.split("\t").map(quoteCsv).join(",")).join("\n"),"csv","text/csv");
    case "csv-to-tsv": return output(engineId,"TSV result",lines(input).map((line)=>parseCsvRow(line).map((cell)=>cell.replace(/\t/g," ")).join("\t")).join("\n"),"tsv","text/tab-separated-values");
    case "list-to-json": return json(engineId,"JSON string array",lines(input));
    case "json-to-list": { const value=parseJson(input); if(!Array.isArray(value))throw new Error("Top-level JSON value must be an array."); return output(engineId,"Text list",value.map((item)=>typeof item==="string"?item:JSON.stringify(item)).join("\n")); }
    case "env-parse": { const result: Record<string,string>={}; for(const line of lines(input)){const trimmed=line.trim(); if(!trimmed||trimmed.startsWith("#"))continue; const index=trimmed.indexOf("="); if(index<1)throw new Error(`Invalid environment line: ${line}`); let value=trimmed.slice(index+1); if((value.startsWith('"')&&value.endsWith('"'))||(value.startsWith("'")&&value.endsWith("'")))value=value.slice(1,-1); result[trimmed.slice(0,index).trim()]=value;} return json(engineId,"Parsed environment values",result); }
    case "http-headers-parse": { const result: Record<string,string|string[]>={}; for(const line of lines(input).filter(Boolean)){const index=line.indexOf(":"); if(index<1)throw new Error(`Invalid HTTP header line: ${line}`); const key=line.slice(0,index).trim().toLowerCase(),value=line.slice(index+1).trim(),existing=result[key]; result[key]=existing===undefined?value:Array.isArray(existing)?[...existing,value]:[existing,value];} return json(engineId,"Parsed HTTP headers",result); }
    case "crc32": return output(engineId,"CRC-32 checksum",crc32(input));
    case "mime-lookup": { const extension=input.trim().toLowerCase().replace(/^.*\./,""); const types:Record<string,string>={html:"text/html",css:"text/css",js:"text/javascript",json:"application/json",xml:"application/xml",csv:"text/csv",txt:"text/plain",svg:"image/svg+xml",png:"image/png",jpg:"image/jpeg",jpeg:"image/jpeg",webp:"image/webp",pdf:"application/pdf",wasm:"application/wasm",zip:"application/zip"}; return output(engineId,"MIME type",types[extension]??"application/octet-stream"); }
    default: throw new Error(`Unknown Batch 4 engine: ${engineId}`);
  }
}

const definitions: Array<[string,string,string,string[]]> = [
  ["character-count","Character Counter","Count UTF-16 units and Unicode code points.",["character","count","utf16"]], ["code-point-count","Code Point Counter","Count iterated Unicode code points.",["unicode","code point","count"]], ["grapheme-count","Grapheme Counter","Count grapheme clusters with Intl.Segmenter.",["grapheme","character","count"]], ["word-count","Word Counter","Count practical Unicode word tokens.",["word","count","text"]], ["sentence-count","Sentence Counter","Estimate sentence count from terminal punctuation.",["sentence","count","text"]], ["paragraph-count","Paragraph Counter","Count blocks separated by blank lines.",["paragraph","count","text"]], ["character-frequency","Character Frequency","Count each Unicode code point occurrence.",["character","frequency","count"]], ["word-frequency","Word Frequency","Count normalized practical word tokens.",["word","frequency","count"]], ["reverse-text","Text Reverser","Reverse text by Unicode code point.",["text","reverse","flip"]], ["reverse-words","Word Order Reverser","Reverse whitespace-delimited word order.",["word","reverse","order"]],
  ["trim-lines","Line Trimmer","Trim leading and trailing whitespace per line.",["line","trim","whitespace"]], ["prefix-lines","Line Prefixer","Add a supplied prefix to every following line.",["line","prefix","add"]], ["suffix-lines","Line Suffixer","Add a supplied suffix to every following line.",["line","suffix","add"]], ["number-lines","Line Numberer","Prefix lines with one-based numbers.",["line","number","list"]], ["filter-lines","Line Filter","Keep lines containing an exact substring.",["line","filter","include"]], ["remove-matching-lines","Matching Line Remover","Remove lines containing an exact substring.",["line","filter","remove"]], ["repeat-text","Text Repeater","Repeat supplied text up to one thousand times.",["text","repeat","duplicate"]], ["truncate-text","Code Point Truncator","Keep the first requested Unicode code points.",["text","truncate","length"]], ["tabs-to-spaces","Tabs to Spaces","Replace tabs with a configured number of spaces.",["tab","space","indent"]], ["spaces-to-tabs","Leading Spaces to Tabs","Convert leading space groups into tabs.",["space","tab","indent"]],
  ["json-validate","JSON Validator","Confirm whether input is valid JSON.",["json","validate","syntax"]], ["json-value-type","JSON Value Type","Report the top-level JSON value type.",["json","type","inspect"]], ["json-object-keys","JSON Object Keys","List top-level JSON object keys.",["json","object","keys"]], ["json-array-length","JSON Array Length","Count top-level JSON array entries.",["json","array","length"]], ["json-pointer-get","JSON Pointer Getter","Resolve an RFC 6901-style JSON Pointer.",["json","pointer","get"]], ["json-array-dedupe","JSON Array Deduplicator","Remove repeated JSON-serialized array values.",["json","array","dedupe"]], ["json-array-sort","JSON Array Sorter","Sort homogeneous string or number arrays.",["json","array","sort"]], ["json-string-escape","JSON String Escaper","Serialize text as one JSON string literal.",["json","string","escape"]], ["json-string-unescape","JSON String Unescaper","Parse one JSON string literal.",["json","string","unescape"]], ["json-lines-to-array","JSON Lines to Array","Parse non-empty JSON Lines into an array.",["jsonl","json","array"]], ["json-array-to-lines","JSON Array to Lines","Serialize array entries as JSON Lines.",["json","jsonl","convert"]], ["json-depth","JSON Depth Calculator","Calculate nested container depth.",["json","depth","nesting"]],
  ["url-parse","URL Parser","Split an absolute URL into standard components.",["url","parse","components"]], ["url-origin","URL Origin Extractor","Return an absolute URL origin.",["url","origin","extract"]], ["url-path-segments","URL Path Segments","Decode and list URL path segments.",["url","path","segments"]], ["url-query-build","Query String Builder","Build a query from key-value lines.",["query","build","url"]], ["url-query-sort","Query Parameter Sorter","Sort query parameters by key.",["query","sort","url"]], ["url-normalize","Basic URL Normalizer","Lowercase host, remove fragment and default port.",["url","normalize","canonical"]], ["url-resolve","Relative URL Resolver","Resolve a relative reference against a base URL.",["url","resolve","relative"]], ["data-url-encode","Text Data URL Encoder","Create a percent-encoded text data URL.",["data url","encode","text"]], ["data-url-decode","Text Data URL Decoder","Decode a non-Base64 percent-encoded data URL.",["data url","decode","text"]], ["domain-extract","Hostname Extractor","Extract the hostname from an absolute URL.",["domain","hostname","url"]],
  ["gcd","GCD Calculator","Calculate the greatest common divisor.",["gcd","integer","math"]], ["lcm","LCM Calculator","Calculate the least common multiple.",["lcm","integer","math"]], ["prime-check","Prime Number Check","Test a signed integer for primality.",["prime","integer","check"]], ["integer-factors","Integer Factor Finder","List positive factors up to a safe input bound.",["factor","integer","divisor"]], ["mean","Arithmetic Mean","Calculate the arithmetic mean.",["mean","average","numbers"]], ["median","Median Calculator","Calculate the median of finite numbers.",["median","statistics","numbers"]], ["number-minmax","Minimum and Maximum","Find minimum and maximum values.",["minimum","maximum","numbers"]], ["number-sort","Numeric Sorter","Sort finite numbers in ascending order.",["number","sort","ascending"]], ["percentage","Percentage Calculator","Calculate part divided by total as a percentage.",["percentage","part","total"]], ["byte-format","Binary Byte Formatter","Format bytes with IEC binary units.",["bytes","kib","format"]], ["roman-encode","Roman Numeral Encoder","Convert 1 through 3999 to canonical Roman numerals.",["roman","number","encode"]], ["roman-decode","Roman Numeral Decoder","Convert canonical Roman numerals to decimal.",["roman","number","decode"]],
  ["date-difference","Date Difference","Compare two date-times in fixed units.",["date","difference","duration"]], ["date-add-days","Add Days to Date","Add a finite day count in UTC.",["date","add","days"]], ["day-of-week","UTC Day of Week","Return the UTC weekday name.",["date","weekday","day"]], ["leap-year","Leap Year Check","Apply Gregorian leap-year rules.",["leap","year","date"]], ["iso-week","ISO Week Calculator","Return ISO week year and number.",["iso","week","date"]],
  ["tsv-to-csv","TSV to CSV","Quote tab-separated cells as CSV.",["tsv","csv","convert"]], ["csv-to-tsv","CSV to TSV","Parse single-line CSV records into TSV.",["csv","tsv","convert"]], ["list-to-json","Line List to JSON","Convert lines into a JSON string array.",["list","json","convert"]], ["json-to-list","JSON Array to List","Render JSON array entries one per line.",["json","list","convert"]], ["env-parse","Environment File Parser","Parse simple KEY=VALUE lines into JSON.",["env","parse","dotenv"]], ["http-headers-parse","HTTP Header Parser","Parse header lines and preserve repeated names.",["http","headers","parse"]], ["crc32","CRC-32 Calculator","Calculate CRC-32 over UTF-8 text bytes.",["crc32","checksum","hash"]], ["mime-lookup","MIME Type Lookup","Map common extensions to MIME types.",["mime","extension","content type"]],
];

export const BATCH4_LOCAL_ENGINES: LocalEngine[] = definitions.map(([id,name,description,keywords]) => ({
  id, name, description, keywords, placeholder: `Enter input for ${name}…`,
  run: async (input) => runBatch4Engine(id,input),
}));
