// AUTO-GENERATED BY src/content-pipeline/compile-published.ts. DO NOT EDIT.
import type { PublishedArtifact } from "../content-pipeline/published-artifact-schema";

export const GENERATED_PUBLISHED_CONTENT: Record<string, PublishedArtifact> = {};
