import React from "react";
import { Bot, FilePlus2, Loader2, Send, Sparkles, User } from "lucide-react";
import { CloudModeBanner } from "./CloudModeBanner";
import type { LocalEngine } from "../../lib/studio/types";
import type { StudioMessage } from "../../lib/studio/types";

const SUGGESTIONS = ["Convert JSON to CSV", "Generate a UUID", "Encode to Base64", "Hash with SHA-256", "Count words and characters"];
interface Props { cloud: boolean; engine: LocalEngine; input: string; command: string; messages: StudioMessage[]; loading: boolean; onInput: (value: string) => void; onCommand: (value: string) => void; onSubmit: () => void; onAttach: () => void; onSuggestion: (value: string) => void }
export function StudioCenterPanel({ cloud, engine, input, command, messages, loading, onInput, onCommand, onSubmit, onAttach, onSuggestion }: Props) {
  return <section className="flex min-w-0 flex-1 flex-col bg-[#F8F7F4]">
    <div className="border-b border-stone-200 px-4 py-2"><CloudModeBanner cloud={cloud} /></div>
    <div className="min-h-0 flex-1 overflow-y-auto p-4 lg:p-8">{messages.length === 0 ? <div className="flex h-full min-h-72 flex-col items-center justify-center text-center"><div className="relative mb-5"><span className="absolute inset-0 rotate-6 rounded-3xl bg-indigo-100" /><span className="relative flex h-20 w-20 items-center justify-center rounded-3xl bg-white shadow-sm"><Sparkles className="h-10 w-10 text-indigo-500" /></span></div><h2 className="text-xl font-semibold text-stone-800">Welcome to XFree Studio</h2><p className="mt-2 max-w-md text-sm text-stone-500">Drop a file and tell XFree what to do. Local tools process your data on this device.</p><div className="mt-7 flex max-w-2xl flex-wrap justify-center gap-2">{SUGGESTIONS.map((suggestion) => <button key={suggestion} onClick={() => onSuggestion(suggestion)} className="rounded-full border border-stone-200 bg-white px-4 py-2 text-sm font-medium text-stone-600 shadow-sm hover:border-indigo-300 hover:text-indigo-600">{suggestion}</button>)}</div></div> : <div className="mx-auto max-w-3xl space-y-4">{messages.map((message) => <div key={message.id} className={`flex gap-3 ${message.role === "user" ? "justify-end" : "justify-start"}`}>{message.role === "assistant" ? <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-white"><Bot className="h-4 w-4 text-indigo-500" /></span> : null}<div className={`max-w-[85%] rounded-2xl px-4 py-2.5 text-sm shadow-sm ${message.role === "user" ? "rounded-br-md bg-indigo-600 text-white" : "rounded-bl-md border border-stone-200 bg-white text-stone-700"}`}><p className="whitespace-pre-wrap">{message.content}</p><p className={`mt-2 text-[10px] ${message.role === "user" ? "text-indigo-200" : "text-stone-400"}`}>{message.provider === "NVIDIA" ? `NVIDIA${message.model ? ` • ${message.model}` : ""}` : "Local"}</p>{message.fallbackNotice ? <p className="mt-1 text-xs text-amber-600">{message.fallbackNotice}</p> : null}</div>{message.role === "user" ? <User className="mt-1 h-5 w-5 text-indigo-400" /> : null}</div>)}</div>}</div>
    <div className="shrink-0 px-4 pb-3 lg:px-8">{!cloud ? <textarea value={input} onChange={(event) => onInput(event.target.value)} rows={4} placeholder={engine.placeholder} className="mx-auto mb-2 block w-full max-w-3xl resize-y rounded-2xl border border-stone-200 bg-white p-3 font-mono text-xs text-stone-800 outline-none focus:border-indigo-300 focus:ring-2 focus:ring-indigo-100" /> : null}<form onSubmit={(event) => { event.preventDefault(); onSubmit(); }} className="mx-auto flex max-w-3xl items-end gap-2 rounded-2xl border border-stone-200 bg-white p-2 shadow-lg focus-within:border-indigo-300 focus-within:ring-2 focus-within:ring-indigo-100"><button type="button" onClick={onAttach} className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl text-stone-400 hover:bg-indigo-50 hover:text-indigo-600" aria-label="Attach file"><FilePlus2 className="h-4 w-4" /></button><textarea id="studio-command" value={command} onChange={(event) => onCommand(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); onSubmit(); } }} rows={1} placeholder={cloud ? "Ask an NVIDIA model…" : "Drop a file or tell me what to do…"} className="min-h-9 flex-1 resize-none bg-transparent px-1 py-2 text-sm text-stone-800 outline-none" /><span className={`mb-1 hidden rounded-full px-2 py-1 text-[10px] sm:block ${cloud ? "bg-indigo-50 text-indigo-700" : "bg-emerald-50 text-emerald-700"}`}>{cloud ? "Cloud" : "Local"}</span><button disabled={loading} className="mb-0.5 flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-indigo-600 text-white disabled:opacity-40" aria-label="Run command">{loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}</button></form><p className="mt-2 text-center text-[10px] text-stone-400">Enter to run · Shift+Enter for a new line</p></div>
  </section>;
}
